### ISSUE TITLE
[Bug]: I am not receiving alert via email nor in the app

### ISSUE THREAD

**Issue by Cris70** [netdata/netdata-cloud#1033]
### Bug description

Alerts are not being sent to the configured email address nor to the mobile app

### Expected behavior

I'd expect to receive alerts in my email and in my app

### Steps to reproduce

1. n/a

### Screenshots

![immagine](https://github.com/netdata/netdata-cloud/assets/5107224/392e7faa-4fd0-448f-a62c-bacc7e3a411f)

### Desktop

OS: Linux
Browser: Firefox
Browser Version: 127.0

### Additional context

I have one warning and one unreachable server as you can see in the screenshot, but no email was sent and no notification appears in the app.

**Comment by sashwathn** [comment]
@Cris70 : Can you please check your notification settings on the profile? If you have set notifications to `Critical` only, you will not receive notification emails..

<img width="475" alt="image" src="https://github.com/user-attachments/assets/7f80e286-fc7c-47cd-b657-e3e95f289606">

**Comment by Cris70** [comment]
Thank you @sashwathn!
This is what I see in my settings:
![immagine](https://github.com/user-attachments/assets/23be7e62-d88c-4a6e-8adb-c07f27d218de)

I see mostly an unpredictable behavior: sometimes notifications do arrive on my phone, but not always. The same happens with email notifications. I have yet been unable to tell if there's a pattern.

Oh, BTW.. why is this bug report marked as closed?

**Comment by sashwathn** [comment]
@Cris70 : Sorry, the bug report was closed by mistake.
Can you please share your space-id for us to investigate this further?

cc: @car12o

**Comment by Cris70** [comment]
> Can you please share your space-id for us to investigate this further?

Sure! 
Our space-id is Bluebiloba.

But I'm now receiving the alerts, so I don't know if you'll be able to debug what happened. 

There's still a bit of unpredictability about alerts however: sometimes they are not transmitted on one of the enabled channels (or both) and I've been unable to find a pattern.

Cris

**Comment by car12o** [comment]
@Cris70 after investigation, I didn't find any problem with your space.

I can see you have two configured notification integration (`Email` & `Mobile App`) and they are working as expected.

I can also see we didn't send any notification on the last 2 weeks. Bear in mind, this doesn't mean Netdata didn't trigger any alert on your infrastructure because I can see it did. **The reason why those alerts didn't dispatch any notification is because those alerts are configured to do not trigger a notification when raised.**

More details here:
https://learn.netdata.cloud/docs/alerts-&-notifications/alert-configuration-reference#disable-or-silence-alerts

In your particular case, your alerts do not trigger a notification as they are configured to be `silenced`.
https://learn.netdata.cloud/docs/alerts-&-notifications/alert-configuration-reference#silence-an-individual-alert

In order to `unsilence` them, please change the `to` property on the specific alerts from `silent` to, for example, `sysadmin`.

I hope this can help you.

I will close the issue since I didn't find any problems/issues on our system.
Feel free to reopen if the problem persists.

**Comment by Cris70** [comment]
Thank you @car12o for the solution and for the extensive documentation.
I'll be sure to review it ASAP.

p.s. I do not remember silencing those alerts. Are they silenced by default? Or, are there other conditions that could cause those alerts to become silenced?

**Comment by car12o** [comment]
Anytime @Cris70, glad to help.

Yes, some of our stock alerts are silenced by default. In order to trigger notifications, you need to change the mentioned setting.

I can see mostly in your space net alerts being triggered, and almost all are silenced by default.
https://github.com/netdata/netdata/blob/docs/cloud-msteams-update/src/health/health.d/net.conf
