### ISSUE TITLE
[BUG] Missing navigation bar after running metric correlations

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#121]
**Describe the bug**
The user started running metric correlations. In the meantime, and while the process was running in the background, he moved to alerts. When he returned back to the node dashboard the process had finished, but the metric correlation navbar with the slider was invisible missing.
The navbar appeared after clicking the green button named metric correlations.

After running metric correlations (missing navebar)
![image](https://user-images.githubusercontent.com/82235632/126675786-9f04aac4-e796-4975-9180-592ae9c67ae3.png)

After pressing the green button
![image](https://user-images.githubusercontent.com/82235632/126676690-ea2efa33-586a-454f-8984-844e124b9987.png)

**To Reproduce**
1. Initiate Metric Correlations by clicking on the button on the Single Node view
2. Select a valid timeframe (between 15 and 180 sec.) and click on Find Correlations
3. While the message "Calculating metric correlations..." is displayed move to another tag, e.g. Alerts
4. When coming back to Single Node view you don't see the area of Metric Correlations enabled so you don't know the status of the process - when the process completes it filters the charts as expected (if user clicks on the Metric Correlations button he can see the state)

**Expected behavior**
When navigating from Single Node view to another tab when some action is being done on Metric Correlations that state shouldn't be lost. This doesn't happen just on the calculating state it also happens after the results are displayed

**Comment by novykh** [comment]
The bug is that it keeps any state of the metric correlations. Navigating to other pages should cancel and reset anything related. We cannot keep any state with the current implementation, since there are multiple moving parts needed to be taken into account. Like changing datetimes, going into other nodes, go again back into the same node through an alarm.
So, the bug is that the state doesn't reset. If we want to keep any state while navigating to other tabs, then we need a new feature request in order to plan and make sure all the use cases will be accomodated.

**Comment by hugovalente-pm** [comment]
@novykh agreed, in this case let's do a reset. Is there a way to notify the user if he moves to another tab the Metric Correlations process being executed will be lost?

**Comment by hugovalente-pm** [comment]
This is closed as per the above discussion
