### ISSUE TITLE
[BUG] Invited user cannot immediately join invited space

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#125]
Steps to reproduce:

1. User A with Space One
2. User B creates account and verifies her email
3. User A invites User B to Space One
4. User B clicks the Join Space CTA in the received email
5. User B visits cloud without an authenticated session
6. User B types her email in the input field and clicks _sign in by email_
7. User B follows the signin link in the Sign In email she received.
8. Instead of directly joining the space she was invited to the user only sees the previous space she was a member of, while a popup shows that User B successfully joined Space One.

There seems to be a race condition here, since this flow doesn't reproduce the issue consistently. 

User B gets re-directed to the invited space Space One, if she re-sign in.

**Comment by cakrit** [comment]
Plz check if it's something on the back-end.

**Comment by novykh** [comment]
> Plz check if it's something on the back-end.

Maybe someone from the backend team is more suitable for this.

**Comment by TonyPath** [comment]
![req_calls](https://user-images.githubusercontent.com/2017356/135814763-b1041590-d58f-4202-993d-a3c254574125.png)

Following the steps to reproduce the issue, i noticed an interesting behavior. FE fires 2 `join-callback` requests. The first one gets cancelled while the second gets completed. 

Now, the fact that the first request gets cancelled from FE side doesn't mean that the request in server has not been received and and eventually processed successfully. Having said that, the second request will fail because the user has already joined the space. This is the reason that I see in logs an entry like the following, in every test i made. 
```
{"time":"2021-10-04T07:41:09.841696745Z","level":"warning","severity":"WARNING","file":"/go/src/github.com/netdata/cloud-spaceroom-service/http/apiencoder.go:197","message":"http error response","svc":"cloud-spaceroom-service-0-55dcf755bc-tpfjl","request-id":"Hs42bl35Re-691599","error":"space invitation not found"}

```
which makes sense. The first request was processed successful, so the invitation got deleted and the second request failed because of `invitation not found` error. 

I didn't manage to reproduce the case where the joining is totally fail, meaning that the user doesn't  because member of space but the aforementioned are flags for race condition situation. Is not predictable at which point of process the first request will reach. 
The process of joining includes some steps to be executed in order. The first step is to delete the space invitation for current user before add him to space members. What if the first request reach up this point and then gets canceled ? Then yes ... bad day for joining.

I believe that I need to sit up with one FE guy and find out why the first gets cancelled and also not firing the 2nd request.WDYT?

cc : @dimko @novykh @jjtsou @manos-saratsis

**Comment by dimko** [comment]
Re-opening this one, as it seems we have again issues with the invitation re-direct and users cannot immediately join the space

**Comment by dimko** [comment]
Re-closing 👯
