### ISSUE TITLE
[BUG] - Sign in to netdata.cloud broken link 

### ISSUE THREAD

**Issue by anastako** [netdata/netdata-cloud#133]
When user selects the link "Sign in to netdata.cloud" the links results in 410 as shown on the video. 

**To Reproduce**	
Try to sign in to netdata.cloud from the top left corner of the agent screen. 

https://user-images.githubusercontent.com/23135936/131507592-34537238-0a13-46cd-8deb-6cf70813c98f.mov

**Expected behavior**	
To sign in to netdata.cloud

**Desktop (please complete the following information):**	
 - OS: MacOS	
 - Browser Edge

**Comment by chrikar** [comment]
Hey @anastako ,

Are you using brew to install the netdata agent by any chance? Because that agent is probably outdated and could cause some problems.
If that is the case I would suggest to either use docker to install netdata as that would be cleanest/fastest solution to get netdata up and running:
https://learn.netdata.cloud/docs/agent/packaging/docker

Or try to install netdata on mac from source:
https://learn.netdata.cloud/docs/agent/packaging/installer/methods/macos#install-netdata-from-source

cc: @Ferroin

**Comment by anastako** [comment]
Thank you! Yes, I used brew indeed! 🙏

I will do what you advised me!

**Comment by manos-saratsis** [comment]
@anastako please install through Kickstart and if it works please close the bug
