### ISSUE TITLE
Beta mode, graphs should displace full scale. 

### ISSUE THREAD

**Issue by densone** [netdata/netdata-cloud#195]
When running beta feature its awesome. But if you are more than 4' from your screen you cant tell if the graph is 20% or 100% 

I suggest scaling the graph up to 100% at all times or at least making an option to do so. 

![image](https://user-images.githubusercontent.com/49484/142717804-32ec6312-5cfb-43eb-9682-44a078e5a3aa.png)

**Comment by hugovalente-pm** [comment]
@densone thanks for reporting this, to confirm also the expected behaviour and then potential feature request, for these charts like Total CPU utilization (system.cpu):
a) if you see them on Overview or Single Node view page with a full Y-axis scale you still want to see them like that on Custom dashboards
b) the feature to enhance would be to allow you to remove that fixed scale or set a fixed scales (for those that didn't already have one)

**Comment by hugovalente-pm** [comment]
we have the customization of y-axis on this ticket https://github.com/netdata/netdata-cloud/issues/789
