### ISSUE TITLE
[BUG] Incorrect space name in reachability notifications emails after space renaming

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#210]
Steps to reproduce:

1. Create a new account
2.  Rename the created space
3. Claim a node in that space
3. Trigger a reachability notification email for the previously claimed node (kill agent)

**Reachability notification email should have the updated space name instead of the original**

**Comment by YaroslavDev** [comment]
@dimko I see this bug was open on 7 Dec 2021, reachability emails back then were sent via legacy `cloud-notification-sender-service` which indeed did not support updating space slug and, therefore, was sending reachability emails with slug set on space creation. Currently, reachability are sent via new `cloud-alarm-notification-sender-service` which updates space slug according and should send emails with correct slug. Can you please re-test? or confirm that bug still persists?

**Comment by dimko** [comment]
@YaroslavDev thanks, this is indeed fixed. Closing it.
