### ISSUE TITLE
[BUG] Charts with special characters not found

### ISSUE THREAD

**Issue by juacker** [netdata/netdata-cloud#226]
**Describe the bug**	
Cannot load charts whose IDs have special characters (colon, slash, equal, etc). The problem is that the chartID is not encoded, so the cloud is not able to find it.

For example, for the chart with ID `prometheus_php-fpm_exporter_local.coredns_dns_request_duration_seconds_bucket|server=dns://10.2.0.10:53,type=A,zone=cluster.local.`:

Currently, the requested URL is `https://app.netdata.cloud/api/v2/nodes/{nodeID}/charts/prometheus_php-fpm_exporter_local.coredns_dns_request_duration_seconds_bucket%7Cserver=dns://10.2.0.10:53,type=A,zone=cluster.local.`

The chart ID should be encoded, and the requested URL should be: `https://app.netdata.cloud/api/v2/nodes/{nodeID}/charts/prometheus_php-fpm_exporter_local.coredns_dns_request_duration_seconds_bucket%7Cserver%3Ddns%3A%2F%2F10.2.0.10%3A53%2Ctype%3DA%2Czone%3Dcluster.local.`

**Comment by juacker** [comment]
This could potentially affect this endpoints (the contexts also have special characters):

- /api/v2/nodes/{nodeID}/charts/{chartID}
- /api/v2/spaces/{spaceID}/rooms/{roomID}/charts/{chartID}
- /api/v2/spaces/{spaceID}/rooms/{roomID}/contexts/{contextID}

**Comment by ShimonOhayon** [comment]
@hugovalente-pm  Here is what i found:

last 24h numbers:

Total requests: 885
return 404: 494 (55.9%)
return 200:  391 (44.1%)

You can edit the query to get more insights https://cloudlogging.app.goo.gl/G7LP1VBVeZ5HneHbA

**Comment by ShimonOhayon** [comment]
I think the results above are only for new arch requests (v2), @juacker  Can you specify similar endpoint for v1 so i can see the logs?

**Comment by juacker** [comment]
If I'm not missing something (@papazach please correct me if I'm wrong) endpoints `/api/v2/nodes/{nodeID}/charts/{chartID}` and  `/api/v2/spaces/{spaceID}/rooms/{roomID}/charts/{chartID}` are only called for new arch agents to get chart details. For old arch ones there is no similar endpoint, as these agents don't store chart details in the cloud, so requests to these endpoints would only affect new arch agents only.

For the context endpoint (`/api/v2/spaces/{spaceID}/rooms/{roomID}/contexts/{contextID}`), I see we support new and old agents, so requests to these endpoints may affect both of them. `v1` for this endpoint exists, but afaik it's not called anymore by the FE.

**Comment by ralphm** [comment]
So these numbers are not actually that representative as we don't have sufficient volume in our new architecture. Possibly a significant portion of those 404s you counted are because I left my dashboard open with these problematic charts in the view port and forcing play.

Not the highest priority, but showing (correct) metrics is the core use case of Netdata. When our frontend devs are back next week, let's assess how much of an impact fixing this would be.

**Comment by hugovalente-pm** [comment]
@ravilushqa thank you for collecting those stats.

@juacker I had asked Shimon to check for old and new arch since we had spoken on the daily that this should affect both cases.  Looking to [Swagger Docs](https://swagger.corp.testing.netdata.cloud/swagger/#/) I see we have:
* a GET `/api/v1/nodes/{nodeID}/charts` but not sure this is used
* a POST `/api/v1/spaces/{spaceID}/charts/_query`

Agreed @ralphm, let's see next week how to prioritize it depending on effort and knowing we want to onboard new users.
