### ISSUE TITLE
[BUG] /data requests initiation delay in single node view

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#239]
if you go to a node page with lots of charts there is a significant delay between the time the initial `/charts` request receives a response and when the individual `/chart` requests and subsequent `/data `requests are issued.

In that specific case there was like ~20 seconds interval

**Comment by dimko** [comment]
@ralphm this is the ticket for the issue you reported.

**Comment by hugovalente-pm** [comment]
@dimko does this happen to all the nodes or you see this happening to particular nodes?

asking this because we have this Building TOC for a Single Node view performance issue #[2655](https://app.zenhub.com/workspaces/product-5ea1534e9ff5df7daace00d5/issues/netdata/product/2655) and also some others with investigations and remediation actions being done due to some Nodes on the Cloud BE having huge number of stale charts (charts that the Agent has already deleted)

**Comment by dimko** [comment]
I think it is related with the issue you tagged @hugovalente-pm. We were discussing yesterday with @ralphm who was the one that reported it. Opened an issue here for external visibility in case other users see it as well.

**Comment by novykh** [comment]
Fixed.
