### ISSUE TITLE
[BUG] Grouping issues in the Overview screen

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#25]
![image](https://user-images.githubusercontent.com/43294513/101043795-8a9bc280-3533-11eb-94b8-5d56e3ccb7d2.png)

We have a few problems with the groupings shown above in the overview screen:

- "group" should be renamed to "cgroups"
- "cgroups" are missing the cgroup network interfaces. e.g. see the following container, it has a "net eth0"
![image](https://user-images.githubusercontent.com/43294513/101044120-dea6a700-3533-11eb-8d92-bf9416001046.png)

- "prometheus" is NOT a group. For each endpoint that we collect data from (e.g. redis), we need a separate grouping.

**Comment by cakrit** [comment]
@jacekkolasa please speak with Ilya about this, it should be easy to fix.

**Comment by jacekkolasa** [comment]
I have limited options on how to group prometheus collectors, because on composition step we loose the `app` information, so the only way I can group is by `job`.

This is how charts are named in node-view:
```
prometheus_prometheus-mongodb_mongodb-sharded-shard0-data-1_metrics_tcp_9216.promhttp_metric_handler_requests_total
prometheus_prometheus-mongodb_mongodb-sharded-shard0-data-1_metrics_tcp_9216.promhttp_metric_handler_requests_in_flight
```

And in overview:
```
prometheus.promhttp_metric_handler_requests_in_flight
prometheus.promhttp_metric_handler_requests_total
```

@cakrit is this intentional? I guess it is, but I want to confirm.

This is what we get when grouping by `job`, which i get from first part of the `family`, for example:
`promhttp_metric` > `promhttp`

![image](https://user-images.githubusercontent.com/5786722/106301600-2d34a100-6258-11eb-92b4-a2b44b6149e4.png)

Is this OK?

**Comment by cakrit** [comment]
This grouping is good! I'm closing and expect to see it live soon.
