### ISSUE TITLE
[BUG]On some composite charts the horizontal axis is jumping 2 mins within secs

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata-cloud#27]
**Describe the bug**	
[BUG]On some composite charts the horizontal axis is jumping minutes, charts change shape and the users cannot follow. Also the resolution changes

**To Reproduce**	
Steps to reproduce the behavior:	Go to Overview -> Disks -> disk.io chart

**Expected behavior**	
The horizontal axis should maintain a set timeframe specified by the date & time picker

**Screenshots**
See video
[Screen Recording 2020-12-03 at 4.38.08 PM.mov.zip](https://github.com/netdata/netdata-cloud/files/5637812/Screen.Recording.2020-12-03.at.4.38.08.PM.mov.zip)

**Comment by jacekkolasa** [comment]
@manos-saratsis this is the expected behaviour (i've rewritten it from old dashboard) because when we have the data we don't know the y-range, we keep only displayed data all the time. There was an idea to add an option for user to set y-range as fixed, or to maintain min/max, but we would need to keep all-time min/max on Agent side.

In other words, I don't know how to fix it without breaking someone's behaviour. Let's talk if you need to progress with that
