### ISSUE TITLE
[BUG] Systems with multiple disk or CPU show aggregate sum temperature

### ISSUE THREAD

**Issue by redfive2012** [netdata/netdata-cloud#274]
**Describe the bug**	
When temperature columns are displayed in the Nodes view for any War Room, for systems with multiple disks or CPUs, the temperature columns show a single graph tracking the total sum of the disk or CPU temperatures. Graphs seem to be aggregated based on the type of dimension -- multiple disk sensors are summed, multiple CPU cores are summed, other sensor types seem to be summed if their dimensions are similar. Systems with multiple CPU _sockets_ show separate graphs for each socket, but the graph traces show the aggregate temperatures of all cores within each socket. There seems to be no way to display individual temperature sensors separately, or to turn off the aggregate summing.

**To Reproduce**	
Add a metric for any temperature sensor class with multiple devices (disk, CPU, IPMI, etc.).

**Expected behavior**	
One graph per temperature sensor, disk, CPU, ICH, IPMI, etc.

**Screenshots**	
![image](https://user-images.githubusercontent.com/1361614/154019166-9301b8e6-981c-4f28-afcc-cd3099295c89.png)
![image](https://user-images.githubusercontent.com/1361614/154019773-20bbe6bb-0702-431a-95d2-1c01256d6ea9.png)

**Desktop (please complete the following information):**	
 - OS: Windows 10 21H2
 - Browser: Firefox
 - Version: 97.0 64-bit

**Additional context**	
A sum total temperature for all disks or CPUs in a system doesn't make any sense. An _average_ temperature, yes, but I'd also like to see the individual temperatures as well. Or if that causes too much resource usage for individual graphs, an average of the selected dimensions would be sufficient, and I can still drill down to the individual readings.

The first attached image shows disk, CPU, and IPMI temperatures for a system with 4 SATA HDD, 12 CPU cores across 2 sockets, and 10 IPMI temperature sensors. If any of the components were actually as hot as the graphs indicate, I'd have a fire in my house.

The second attached image shows the tooltip for one of the 2 CPU graphs, showing the context, dimensions, and aggregate function used. Editing the column does not give the ability to change the aggregate function.

**Comment by ktsaou** [comment]
Hi @redfive2012. Thank you for reporting this. You are right. The current implementation is very limited, because it flattens entire charts into one value, by summing all the dimensions together. Even if we did an average, it wouldn't be that nice.

I think we need to change our approach here.

I understand that what is important is the individual *current* value, not the chart. So, the moment you add `sensors.temperature`, we could add something like this to the node info:

```
[ coretemp.isa-0000.temperature                      ]
[ Core0: 37, Core1: 38, Core2: 42, Core3: 39 Celsius ]
``` 

Probably with a little sparkline as watermark behind each dimension (Core0, Core1, Core2, Core3).

And if there are too many dimensions and they can't fit in a raw, it could wrap like this:

```
[ coretemp.isa-0000.temperature                      ]
[ Core0: 37, Core1: 38, Core2: 42, Core3: 39         ]
[ Core4: 35, Core5: 34, Core6: 40, Core7: 36 Celsius ]
``` 

What do you think about the values to be presented:

1. These values should ignore the datetime picker, they should always be the latest, refreshed at data collection frequency (e.g. every second), and they should never interact with other charts (i.e. hovering on other charts, does not affect them).
2. These values should respect the datetime picker, and they should work like the gauges at the top of every netdata dashboard  (so, if you zoom out they represent an average of a longer duration, and if you interact with any chart they show they value at the time selected on the other chart).

Which one of the 2 is better for you?

**Comment by ktsaou** [comment]
@hugovalente-pm @vinnygats we have to take into account this for the improved nodes page.

**Comment by redfive2012** [comment]
For the nodes page, choice #1 seems like it would be sufficient. If someone
is trying to track a processing issue and watching the temperatures spike
in response, they'd probably be on the full chart page already, not
watching the nice page with its shorter timeframe and no history replay.
Tracking the current values in the small charts should be enough, I would
think.

**Comment by hugovalente-pm** [comment]
with the recent work done on the Nodes tab the individual charts have been "merged" as composite charts, not stating this saying this will solve the issue it is more as N/A atm

there is follow-up work to help bring more flexibility to this here https://github.com/netdata/netdata-cloud/issues/560

closing the bug for now as `won't do` since we aren't doing anything specific, we are reviewing this tab as overall UI/UX
