### ISSUE TITLE
[BUG] User reports receiving alert notifications from cloud, despite setting to not receive them

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#339]
> last night emails started to pile up on my account linked to netdata
> cloud. The profile settings are set to off/red on "Netdata will send
> health notifications via e-mails". This setting seems to be ignored or
> something else changed last night. Could you take a look at this please
> as it is quite noisy!

The identifier of the account is shared in private (alerts team slack channel), for security and privacy reasons

**Comment by lokerhp** [comment]
I've also encountered this, never got email's on a specific email address, until yesterday at around 4pm UTC.  
I've sent @papazach the identifier of the account.

**Comment by car12o** [comment]
In this specific case, all users belonging to the space have email notifications enabled so the Could is in fact honoring those settings. The fact that the user starts receiving notifications is related to the new architecture space migration as the time user started receiving emails matches with the time space was migrated (`2022-03-09 15:48`). We may have a bug in the legacy flow but since now the space is using the new architecture, everything should work as expected.

Although it's not the case for this user, we do have an edge case where we may send notifications where we shouldn't.
As we can see from [this example](https://github.com/netdata/netdata/blob/091dd8c38f3b461b7c96f217b7db7af25b29de34/health/health.d/ram.conf#L28), most Netdata default alarms configurations have a delay in de-escalations where we do not notify the user right away and we delay/debounce this notification, as it could be a false positive transition.
The edge case relies on the fact that we only validate user & space settings when generating a notification from an alarm transition, and we do not re-validate those settings when processing the delayed notification. So if the user updates those settings while the delayed notification was already produced, they will not be taken into account and the email will be sent anyway.

**Comment by cakrit** [comment]
User reported that the issue is resolved now.
