### ISSUE TITLE
[BUG] Unreachable node in Cloud from Agent email alert notification

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#341]
## Describe the bug
From the work introduced on the Agent email alert notification redirect (after user presses "Go to chart") - netdata/cloud-frontend#295 - if the node is claimed to Cloud and user has access to it he gets the "Unreachable node" error page if the node is not accessible at the moment

**To Reproduce**	
1. Claim a node to Netdata Cloud
1. Have an alert triggered from the Agent
1. "Force" the node to be unreachable on Cloud (e.g. delete the `/netdata/cloud.d` dir)
1. On the email alert notification click "Go to chart"
1. See that you get to the "Unreachable node" error page in Cloud

### Scenario 1. Node accessible and reachable on Cloud with data to for specific chart

The user should be redirected to Cloud only when the:
* node is **live** or **stale**, meaning that we can query data for that node
*  user has **access** to one or more Spaces / War Rooms

If more than one Space / War Room is available a list should be presented to the user so he can choose to which Space / War Room he wants to go.

### Scenario 2. Node accessible and reachable on Cloud but no date for the specific chart

The user should be redirected to Cloud only when the:
* node is **live** or **stale**, meaning that we can query data for that node
*  user has **access** to one or more Spaces / War Rooms
*  there **isn't data available** for the specific chart

A button should exist so user can go and see the alert on the Agent dashboard

### Scenario 3. Node is not reachable on Cloud or user doesn't have access

We should attempt to redirect the user to the Agent dashboard directly.

## Screenshots	
N/A

## Error logs	
N/A

## Desktop (please complete the following information):	
N/A

## Additional context
N/A

**Comment by hugovalente-pm** [comment]
@amalkov @jacekkolasa @novykh @juacker the discussion of what we want to do on the technical side, in order to simplify the work on the FE we would the BE to provide:
* list of Spaces / War Rooms the node is claimed to (sending the slugs not ids)
* ensure the above list takes into consideration the user access conditions to those Spaces / War Rooms
* for each entry share the flags of the node `queriable` and `live`

@ktsaou we wanted to check with you the scenario Scenario 2., what do you think?

**Comment by juacker** [comment]
In order to start adding the information requested, what do you think about adding a new field called `authorizedNodes` on `/user_access` requests, where we can return the necessary information?

Initially, I'm thinking about adding the `unreachable` flag, in order to the agent to avoid redirecting to the cloud. The response payload would be this one:

```json
{
  "userStatus": "expiredLogin",
  "userNodeStatus": "accessOK|noAccess",
  "authorizedNodeIDs": [] // TODO: remove when FE starts using authorizedNodes field.
  "authorizedNodes": [{
    "id": "<nodeID>",
    "unreachable": "<boolean>"
  }]
}
```
We can then add to each authorized node item more fields, like the space and room slugs, etc, wdyt?

**Comment by ktsaou** [comment]
I think the front-end should take the decision.

So, we do the `/user_access` call and we get a response that `userNodeStatus: accessOK`.

The front-end then should do the same it does for Visited Nodes to verify the node is actually reachable. I don't think we should add anything more to the response.

Remember that this response is candidate for a security issue, because data returned as also passed across an iframe at the agent. https://github.com/netdata/product/issues/2870

**Comment by jacekkolasa** [comment]
@hugovalente-pm @ktsaou If node is unreachable AND we couldn't find Agent URL in Visited Nodes, are you OK with redirecting to Cloud anyway? If not, we would only leave user with blank (white) page with short description
```
Sorry we cannot find your Agent in the Netdata Cloud visited nodes. To continue please connect your node in the <a href="/">Netdata Cloud</a>
```
If we redirect user to the Cloud, at least they will see more friendly UI

**Comment by hugovalente-pm** [comment]
> Scenario 3. Node is not reachable on Cloud or user doesn't have access
We should attempt to redirect the user to the Agent dashboard directly.

@jacekkolasa what you describe somehow seems to be a sub-step on the above scenario, right?
What you are saying is when we don't have the URL and can't direct the user to the Agent dashboard?

If we redirect him to the Cloud could you confirm what the user will see?

**Comment by jacekkolasa** [comment]
@hugovalente-pm Currently if node is unreachable, user will see "This node is unreachable" screen in Node Tab

If we change that behaviour, and at the same time that Agent will not be found using Visited Nodes API, user will see just "Sorry we cannot find your Agent in the Netdata Cloud visited nodes. To continue..."

My suggestion is to not change current behaviour when Agent is not found in Visited Nodes.

**Comment by hugovalente-pm** [comment]
ok, sounds good your suggestion @jacekkolasa

**Comment by jacekkolasa** [comment]
We synced with @hugovalente-pm and decided to do the following:

- if node is unreachable:
  - see if we have any Visited Nodes (Agents) in history. If any can be pinged, redirect to Agent (FTR for it to succeed, Agent needs to be hosted under https://, otherwise browser will not allow pinging from https://app.netdata.cloud to the Agent)
  - if no Agent can be pinged, display list of Agents as well as links to the Cloud, so user can choose where to redirect
  - if there is no Agents in Visited Nodes, redirect to Cloud.
- We will not check if alert's chart has data, because 1) there's too much work to get metrics data in the redirect script, 2) if there is no data for the Chart, it won't be available both for Cloud and Agent, so there's no real difference here

**Comment by dimko** [comment]
@jacekkolasa just a follow up. What is the status for this one?

**Comment by jacekkolasa** [comment]
I'm unassigning myself from this ticket since I won't be available in next week. I'll gladly finish this work when i return, but if we want to have it finish earlier, here's my working branch: https://github.com/netdata/cloud-frontend/tree/more-precise-redirect
