### ISSUE TITLE
[BUG] in anomaly advisor, the error conditions for metric data is missing

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#358]
1. There is a min of 60 seconds to query Anomaly rates of related metrics. There shouldn't be any min or max duration
2. When we query for Anomaly rates of related metrics, there should be a spinner
3. When the query for Anomaly rates of related metrics fails, there should be a message

**Comment by hugovalente-pm** [comment]
For point 3. we need to check this figma's initial proposal https://www.figma.com/file/MgDDTMmnlulK6Fjoq6LCQF/Anomaly-detection-ideation?node-id=1318%3A196027 and do it or something similar

cc/ @shyamvalsan @christophidesp

**Comment by shyamvalsan** [comment]
I think in the scenario Kosta encountered we don't return anything due to a failure not due to there being no anomalies. So maybe along the same lines you suggest @christophidesp but the message is "Failure to load anomalies" or something along those lines. @hugovalente-pm how do we generally handle error messages in netdata-cloud? Do we suggest the user reload or try again? 

Also, if for selected time period anomaly rates are always zero - indicating no anomalies at all during the selected time period then maybe we should have a "No anomalies detected during this time period" message as well.

**Comment by hugovalente-pm** [comment]
sorry I misread the point 3., I was thinking when we don't have anomalies for some reason but not because of a failure, so @christophidesp suggestion for that sound good

when there are errors on getting data it depends:
* if on getting data for the charts we show an `Error` pill on the top-left corner of the chart
* if on getting charts for an entire dashboard, typically a 5XX or something we show an error page like [this](https://www.figma.com/file/K7NXAai81Ykt1KIDRaYA8l/%232442-%232443?node-id=202%3A3448)
* we also have some errors appearing on a toaster on the bottom-right corner of the app, but I think we want to move away from those

if the error is just on the Anomaly rates of related metrics section we should have a means to show that specifically there and we could allow the user to re-trigger that request `Try again` button or something

**Comment by shyamvalsan** [comment]
@libekonst could you confirm the below - and if this is true, please close this ticket.

Of the items @ktsaou raised in this ticket. 

#1 - fixed in https://github.com/netdata/cloud-frontend/issues/3111
#2 - fixed in https://github.com/netdata/cloud-frontend/issues/3257
#3 - fixed in https://github.com/netdata/cloud-frontend/issues/3257 & https://github.com/netdata/cloud-frontend/issues/3258

cc: @[andrewm4894](https://github.com/andrewm4894)

**Comment by libekonst** [comment]
All three items are now resolved.

The use case for issue **no. 1** should be covered by the 60s window offset implemented in https://github.com/netdata/cloud-frontend/issues/3111

**no. 2** and **no. 3** are directly fixed by https://github.com/netdata/cloud-frontend/issues/3257 & https://github.com/netdata/cloud-frontend/issues/3258
