### ISSUE TITLE
[BUG] charts with update_every=5 get misaligned across nodes, from time to time

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#373]
https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview

![image](https://user-images.githubusercontent.com/2662304/161108063-9b87483d-8d91-44b7-9be1-402ddc022306.png)

With `update_every=5` netdata agents should be aligned to 00, 05, 10, 15, 20, 25, 30, 35, 40, 45 50 and 55 seconds, according to wall clock.

However, some queries return data shifted by a second:

![Peek 2022-03-31 19-51](https://user-images.githubusercontent.com/2662304/161108675-208fa331-2af0-4b82-b722-20617422e0d1.gif)

Note on the chart above:

19:50:10 is aligned, but on the next refresh there are 2 points: 19:50:10 and 19:50:11
similarly
19:50:20 is aligned, but on the next refresh there are 2 points: 19:50:20 and 19:50:21

---

This has another side effect, that when switching to group `by node`, the chart becomes invisible but the data ARE THERE !!!

![Peek 2022-03-31 19-57](https://user-images.githubusercontent.com/2662304/161109914-21fccf3b-3669-4f78-9cd5-a40b7584eb7e.gif)

**Comment by papazach** [comment]
Hello @ktsaou I understand the issue, sadly I try to reproduce it and I cannot.

I've been checking this chart (and others also) in all the rooms I have access to and I haven't bumped onto a similar case to investigate and debug.

In all the cases I came across, the time intervals of the timeseries data response were the same as the `update_every`

**Comment by ktsaou** [comment]
I see it happening now: https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_system_submenu_load&_f=&metrics_correlation=false&after=-900&before=0&utc=Europe%2FAthens&offset=%2B3&timezoneName=E.%20Europe

**Comment by papazach** [comment]
Adding here what I managed to get from intercepting some problematic responses.
This is not an issue that is happening frequently and I think that it is highly likely that it is due to the data (mainly their timing) returned by _some_ nodes.

I quickly put together a script to print the time intervals between the various points of the composite data responses.

The ok cases look like this (note that different time periods were picked from the datepicker affecting the time interval between points consecutive points):

![Screenshot 2022-04-04 at 10 02 04 AM](https://user-images.githubusercontent.com/8328670/161490313-cee8d4cf-b36a-44e0-8f5d-5c301f7a9c31.png)

![Screenshot 2022-04-04 at 10 02 48 AM](https://user-images.githubusercontent.com/8328670/161490426-f7dc6440-251d-4963-983e-bf5e1235ad95.png)

whereas a problematic case looks like this (file):

[res.log](https://github.com/netdata/netdata-cloud/files/8407433/res.log)

Notice the intervals fluctuating and not being stable across the time series.

Will pause this for now to work on some higher prio issues that came up and will resume working on this, hopefully to pinpoint the offending nodes or the circumstances due to which this issue might occur.

**Comment by stelfrag** [comment]
https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview

A small change was made to handle this (I am still checking) So far

![image](https://user-images.githubusercontent.com/52996999/167665455-6f094ae9-35cb-468b-b8b8-716e8884af15.png)

**Comment by stelfrag** [comment]
PR https://github.com/netdata/netdata/pull/12870
