### ISSUE TITLE
[Bug]: Chart name not displayed in Custom Dashboards when chart has error

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#418]
### Bug description

When chart can't load due to an error in /data request we display the (error) badge but we don't show the name of the affected chart.

### Expected behavior

The chart name should be displayed

### Steps to reproduce

1. Navigate to Custom Dashboards
2. Create a custom Dashboard
3. Add a chart that gives errors 

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/167137774-912a6911-0819-4bac-8bb6-56017069b51f.png)

### Error Logs

No error Logs

### Desktop

OS: Linux
Browser: Chrome
Browser Version: 101

**Comment by dimko** [comment]
Ok so we move this to cloud backend, or we decide if we'll show something different.

**Comment by novykh** [comment]
@jjtsou please use the card cached values on the dashboard charts.

**Comment by juacker** [comment]
reading @novykh last message I understand the solution will be implemented FE side only. Just to validate, as I see the `cloud-backend` tag, is there anything pending from the BE side here @hugovalente-pm?

**Comment by hugovalente-pm** [comment]
yes, for now, we are discussing just showing info based on what Cloud FE has:
* Single Node chart - show whatever information we have available, chart title, node name, etc.
* Composite chart - show the `context` 

I know @jjtsou is tackling a similar case but for a different ticket https://github.com/netdata/netdata-cloud/issues/356, where we spoke about probably just showing context, since the example is for an unreachable node 

I'll update the label
