### ISSUE TITLE
[Bug]: User profile doesn't appear if the collapsible list of rooms etc is collapsed 

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#421]
### Bug description

If you collapse that horizontal bar with the rooms, bookmarks etc and click on the bottom left to see the user profile, the pop up doesn't appear. It appears just fine with the thing expanded.

### Expected behavior

Always show the options when a user clicks the bottom left button. 

### Steps to reproduce

1. Collapse the navigation area
2. Click on user profile circle to bring up the options
3. Nothing appears

### Desktop

Latest Chrome on Windows

**Comment by novykh** [comment]
@burbuli8ra maybe we forgot the instantiation of the popover inside the sidebar?

**Comment by burbuli8ra** [comment]
@novykh we didn't do any updates on the user profile avatar and the actions triggered!
Also @cakrit I checked it as well and it works ok for me!

https://user-images.githubusercontent.com/38426486/167917901-e7427c0e-4f8f-4840-9507-7c979b07f3e6.mov

**Comment by cakrit** [comment]
I know what happened. It is black on black and I was on a page where it was completely unnoticeable. Can we perhaps make its background exactly the same as the one of the pop up from the `?` button? That is much more noticeable.

**Comment by ivangergo3** [comment]
@dionysis-netdata @vinnygats What do you guys think about the change?

**Comment by burbuli8ra** [comment]
@cakrit there is an open [PR](https://github.com/netdata/cloud-frontend/pull/3390) that implements the change you suggested!
From my side, I believe that the UI of the app feels more solid now with this change, since both menus are more similar, but I am not sure if it actually solves the initial mentioned issue, since the background can still be mixed up with the background color the **Home** tab uses at some places.

Please let me know what you think, in order to merge or close the related PR (and rethink a solution)! 🙏 

cc: @dionysis-netdata , @vinnygats and @christophidesp

**Comment by christophidesp** [comment]
Hi @cakrit, I think also that what makes the `?` pop-up to stand out more is that we darken the background with an overlay, so the focus turns more to that element
In order to visually differentiate the profile dropdown from the background I added a slight border, which I think helps with decoupling. What do you think?
<img width="824" alt="Screenshot 2022-05-18 at 10 51 27" src="https://user-images.githubusercontent.com/96468003/168999909-bd88c66f-0c65-44bf-baab-c71aade41b57.png">
<img width="490" alt="Screenshot 2022-05-18 at 10 56 46" src="https://user-images.githubusercontent.com/96468003/169000111-07091d50-cadb-4f43-bf78-71fde68ba7f7.png">

**Comment by burbuli8ra** [comment]
@christophidesp I think the best solution would be to add the overlay that shows up when clicking the help/documentation section (`?`) on the profile menu as well! This way the experience our users have with both menus are quite similar and we keep the app's consistency!
I have made the updated suggested and included it on my PR's description as video, so please let me know what you think in order to merge it if you are ok with it!

**Comment by christophidesp** [comment]
I think that it looks a lot more clear now @burbuli8ra!

**Comment by burbuli8ra** [comment]
Great @christophidesp !
Thanks for the reply! I'll ping the PR's reviewers to check it once more (since the initial implementation has changed) and will proceed with merging it! 😄

**Comment by burbuli8ra** [comment]
Released on [v2.30.5](https://github.com/netdata/cloud-frontend/releases/tag/2.30.5)
