### ISSUE TITLE
[Feat]: Add further filtering options on the composite chart bar

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#434]
### Problem

We currently only provide filtering capabilities over `dimensions` on the composite chart bar, so users are limited on slicing capabilities.

### Description

We want to provide users with better slicing capabilities over composite charts, for that we need to allow the user to filter on:
* dimensions - already existis
* data sources (instances)
* nodes - this is chart specific filtering (not to confuse with Global Node filtering)

**On Overview screen** these new filters should work like the dimensions ones, where the user doesn't save them (for example, on page refresh default selections are done).

**On Custom dashboards** these new filters should work like the dimensions ones, when user makes a selection that configuration must be stored.

### Importance

really want

### Value proposition

By adding more filtering options we will allow users to better slice the data presented on composite charts

**Comment by hugovalente-pm** [comment]
This ticket needs to be tackled after [Feat]: Structure the composite chart bar in a way as if it was being explained in written English https://github.com/netdata/netdata-cloud/issues/432 .

**Comment by jacekkolasa** [comment]
@hugovalente-pm, cc @amalkov @ralphm please confirm if this behaviour is ok for Nodes filter:

1. On Global Nodes filter user selected node1 and node2
2. On chart filter we see all nodes in the dropdown, with node1 and node2 preselected
3. Order of the nodes is the same in local filter as in global filter, ie. selected nodes do NOT move to the top (we order filters differently in alerts, where selected items move automatically to the top)

As soon as user starts modifying local filter, it is "detached" from the global filter.
4. User can locally node3 and deselect node2.
5. Any changes in global filter will now NOT impact the chart filter that has "dirty" state
6. If user press "reset" button on the chart filter-bar, then chart filter will again mirror global filter state.

Since the "dirty" state can be missed by the user, and they will wonder why changing global filter doesn't impact one particular chart, i suggest that maybe we'll mark `dirty` filters, for example with different font color, background or border?
cc @PanosJee 

I'll deploy this soon (today) to staging so you can test it.

**Comment by ralphm** [comment]
I kind of expected the list of nodes presented are the ones selected in the global filter only. Mainly because when we have more filter options in the global filter (e.g. on labels), things would be more predicable that way.

That said, your approach also has merit, and maybe we should just try it first.

**Comment by ralphm** [comment]
Or mark the selected-but-now disappeared options ~~differently~~.

**Comment by jacekkolasa** [comment]
@juacker unfortunately we will need to have one more change from BE (in addition to `chartID-nodeID` filters for Instances dropdown).

Can we have `all_nodes` property in /data return payloads, just like we have `all_dimensions`? The reason is that for some charts we'll make the first /data call already requesting filtering by `nodeIDs`, but we want to see all possible nodes for this context, when data returns.
To reduce the payload, we could change current `nodes` to provide only `nodeIDs`. (If you're ok we could have first `nodeIDs` and after FE work remove `nodes` array)

**Comment by hugovalente-pm** [comment]
additional, there was this request:

> Req.: filter composite charts data call with multiple chartIDs? I see filter.chartID works, but only accepts string, not array

> at the moment it only can filter one single chart, we use this parameter to request the chart to the agent, and the agent only accepts one too at the moment
> we could implement at charts filter, but currently is not there yet
> As instances will belong to the same context, maybe we can request context data to the agent and filter the results, so no change in the agent is needed.

it was considered to be done on Cloud BE but it is a move away from pushing the work that can be done directly at the agent. would it be possible to allow on the Agent to make `/data` requests where a filter would be applied on chartIDs?
e.g.: `disk.io context`
* disk.nvme0n1 @netdata-parent-7dc75fdf67-rfpn
* disk.nvme1n1 @netdata-parent-7dc75fdf67-rfpn
* disk.nvme2n1 @netdata-parent-7dc75fdf67-rfpn
* disk.nvme3n1 @netdata-parent-7dc75fdf67-rfpn

allow to filter on specific chartIDs from one and/or multiple nodes

**Comment by hugovalente-pm** [comment]
@jacekkolasa for the message to appear at the bottom of the `instances` dropdown when we have at least one node that doesn't have the capability to filter by multiple chartIDs (TBD) was thinking a line on the bottom like this saying
> You have at least one node that doesn't support filtering chart data by instances. Please check if any is below version v1.36.1.... here.

Notes:
- here ideally would be a link to Centralized Admin Interface on the Room Nodes tab (last image)
- open question is if we should/could only disabled the instances of the nodes that don't support that. 
   - This is tricky one on a Parent-Child setup if, for example, the parent is having the data for a Child and parent has the capabilities but the child doesn't...

![image](https://user-images.githubusercontent.com/82235632/195394195-2ef7a8ff-5a74-4b65-a6bb-d20d1f7b8463.png)

https://app.netdata.cloud/spaces/netdata-cloud/settings/rooms/k8s-prd
![image](https://user-images.githubusercontent.com/82235632/195394676-efb7a0e6-ac53-4a44-bcd4-3e16906e7e6f.png)

**Comment by hugovalente-pm** [comment]
if I'm not mistaken it was @ktsaou that was going to work on that, @ktsaou do you have any thoughts on how the agent API will expose the possibility to make `/data` requests allowing the filtering per multiple instances (chartIDs)?

**Comment by stelfrag** [comment]
> if I'm not mistaken it was @ktsaou that was going to work on that, @ktsaou do you have any thoughts on how the agent API will expose the possibility to make `/data` requests allowing the filtering per multiple instances (chartIDs)?

Check https://github.com/netdata/netdata/pull/13697 

Item 2 -->  `support for querying multiple charts`

**Comment by hugovalente-pm** [comment]
@juacker the work that was pending on the Agent is merged, can we unblock FE by progressing with the BE work?
cc/ @jacekkolasa

**Comment by juacker** [comment]
thanks for the heads-up @hugovalente-pm, I have the PR draft ready, will test it today and publish it. Hope to have it approved and deployed by tomorrow.

**Comment by jacekkolasa** [comment]
@hugovalente-pm  When do you think we can release it, considering Agent release cycle? Should we maybe wait about 1-2 weeks after stable release with that change will land?

**Comment by hugovalente-pm** [comment]
@jacekkolasa I think we had discussed this in the past on this comment https://github.com/netdata/netdata-cloud/issues/434#issuecomment-1276428087 can you check what is possible? we can jump on a call if needed

**Comment by jacekkolasa** [comment]
@hugovalente-pm Sure it will be possible, but I'm wondering if we should show this message when this feature will be completely unavailable for users using stable releases

**Comment by juacker** [comment]
@stelfrag the agent is not returning the `chart_ids` field if we filter by only one chart, the cloud needs it in order to generate the proper dimension names.

- filtering by multiple charts:

![Captura desde 2022-10-24 15-11-40](https://user-images.githubusercontent.com/2930882/197537419-3c85073e-1fa3-4ba5-81b1-5802361b0d8b.png)

- filtering by one chart only:

![Captura desde 2022-10-24 15-10-56](https://user-images.githubusercontent.com/2930882/197537467-48cd3d1d-e3aa-4c85-837a-2e9e8c874d25.png)

**Comment by ktsaou** [comment]
Fixed it at https://github.com/netdata/netdata/pull/13879

When a single chart was given in a context query, the query engine mistakenly was turning the query from a context query to a chart query.

When both chart and context are given, the query engine now run the query as a context one, with a chart filtering.

**Comment by ktsaou** [comment]
https://github.com/netdata/netdata/pull/13879 is merged.

**Comment by ktsaou** [comment]
Let me know if you need something more about it.

**Comment by ktsaou** [comment]
The `full_XXX` members are also filtering the chart(s) given. Do you need this list to always include all charts that would be included in the query without the charts filtering?

**Comment by juacker** [comment]
> The `full_XXX` members are also filtering the chart(s) given. Do you need these arrays to always include all charts that would be included in the query without the charts filtering?

@jacekkolasa the cloud is returning the `full_XXX` attributes @ktsaou mentions as `all_dimensions` and `all_chart_labels`, should the charts filtering affect them?

**Comment by hugovalente-pm** [comment]
@juacker @ktsaou afaik we should be consistent across these `all_xxx` fields if I look into the example of `all_chart_labels` when I filter for a specific node it is only returning the values based on the filters provided FE is keeping a kind of a _cache_ of the entire values from the initial call

![image](https://user-images.githubusercontent.com/82235632/197734760-9ac5783d-be6c-48ec-9e06-5581c82b3dc0.png)

but let's also see what @jacekkolasa has to say

**Comment by juacker** [comment]
BE part released and deployed to production

**Comment by jacekkolasa** [comment]
@juacker @ktsaou I think `all_xxx` should always be the same, regardless of filters passed to the request

**Comment by hugovalente-pm** [comment]
> @juacker @ktsaou I think all_xxx should always be the same, regardless of filters passed to the request

when you say the same you mean the full list without considering filters? I think this was discussed when we were implementing filtering with chart labels and it was decided to be implemented as it is, not sure if it was a technical limitation. 

if we think for FE it is the best approach and UX then let's question @ktsaou. @ktsaou is there  a technical limitation on the `all_xxx` to always have the full list of values independent of the filtering passed to the Agent?

**Comment by ktsaou** [comment]
Implemented it: https://github.com/netdata/netdata/pull/13886

**Comment by hugovalente-pm** [comment]
Agreed @ktsaou but we have a concern on the `all_chart_labels` because from what I know it doesn't behave the `dimensions` and now `charts`, it behave like the contexts

@jacekkolasa @juacker @ralphm and me were discussing this on the daily let me book a slot

**Comment by juacker** [comment]
As discussed with @jacekkolasa and @amalkov, if multiple filters are set in the request (`nodeIDs` and `nodeChartInstances`), the cloud will calculate the nodes to request data to applying the intersection between both of them.

[This PR](https://github.com/netdata/cloud-charts-service/pull/400) implements that behaviour.

**Comment by juacker** [comment]
:point_up_2: deployed to production

**Comment by hugovalente-pm** [comment]
this is released
