### ISSUE TITLE
[Bug]: Chart plays after user lands in single node view through Go to Chart/Run correlations

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#499]
### Bug description

After a user clicks on an alert and selects to run correlations around the alert duration or go to chart for that alert, the datetimepicker is supposed to PAUSE after user lands in single node view

### Expected behavior

datetimepicker should be PAUSE after user lands in single node view after clicking go to chart/run correlations and chart shouldn't be getting udpated

### Steps to reproduce

1. Navigate to Netdata Cloud
2. Claim an agent
3. Trigger an alert to that agent
4. Open the alert's details modal by navigating to Alerts tab and clicking the desired alert name
5. Click view dedicated alert page
6. Click either Go To Chart or Run Correlations
7. In single node view move the mouse around, chart initially paused, starts playing

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/177543858-01be2211-8cc4-45cd-aace-c690132b5928.png)

### Desktop

OS: MacOS
Browser: Chrome
Browser Version: 103

**Comment by novykh** [comment]
The paused on alerts specific pages is artificial, this means when the user clicks on another tab (single node) and it was on PLAY before going to alerts, the datetime picker will go back to PLAY again. @jacekkolasa since you are the assignee here, we will need to to an extra action before redirecting the user to actually PAUSE the datetime picker.

**Comment by dimko** [comment]
This is fixed. Closing
