### ISSUE TITLE
[Bug]: cant remove node

### ISSUE THREAD

**Issue by jonknud** [netdata/netdata-cloud#509]
### Bug description

I am happy that there is a function to remove nodes now.

It worked for a couple of nodes but for one of the nodes it does not work.

![image](https://user-images.githubusercontent.com/28842347/178685122-0a3611ab-78fb-4959-80bb-634424dc9a41.png)

### Expected behavior

I can remove nodes.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/28842347/178685069-cf4dd420-57f4-469b-8ba6-86244cfe645f.png)

### Desktop

OS: Windows 10
Browser Vivaldi
Browser Version latest

**Comment by dimko** [comment]
I've identified the issue. Indeed for some nodes that are supposed to be offline, status is reported as online although it's marked in the UI as unreachable. Thanks again for reporting.

**Comment by dimko** [comment]
The nodes the user is trying to delete are **Stale** and not **Offline**.
**Stale** nodes can't be deleted as per design and implementation. This can change in the future. 

The problem and big confusion comes due to the following issues https://github.com/netdata/netdata-cloud/issues/513 and https://github.com/netdata/netdata-cloud/issues/512. Stale nodes appear as offline in Home screen, also inside the Manage Room modal we display only the **Unreachable** label next to node's name so it's not easy for the user to understand that this node is **Stale**. 

I believe we need to enhance the UX. Tagging @shyamvalsan, @christophidesp and the @netdata/cloud-fe team for this.

**Comment by burbuli8ra** [comment]
@dimko thank you for your detailed explanation about the issue!
We have made a change to the FE to display the correct status of the node inside the pill, when it is unreachable!

So, on the next release the **Unreachable** label will be updated to either **Offline** or **Stale** in order for our users to be able to understand why the **Delete** action is not available when they are selecting a node that is not **Offline**.

**Comment by burbuli8ra** [comment]
Released on [v2.35.20](https://github.com/netdata/cloud-frontend/releases/tag/2.35.20)

**Comment by jonknud** [comment]
Great and not great, now it shows stale.

How can I remove a stale node?

**Comment by burbuli8ra** [comment]
@jonknud currently it is not possible to delete a stale node from a space.
Also, apologies for the late response to your question.
