### ISSUE TITLE
[Bug]: Invitation emails violate the netdata SPF 

### ISSUE THREAD

**Issue by aathan** [netdata/netdata-cloud#530]
### Bug description

Invitation emails should be deliverable, but they seem to violate SPF policies of the sending domain.

```
Aug  1 16:52:03 ip-172-31-36-108 policyd-spf[1404019]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud;ip=208.117.61.246;r=<UNKNOWN>
Aug  1 16:52:03 ip-172-31-36-108 postfix/smtpd[1404013]: NOQUEUE: reject: RCPT from dhtrpdfs.outbound-mail.sendgrid.net[208.117.61.246]: 550 5.7.23 <username@domain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud;ip=208.117.61.246;r=<UNKNOWN>; from=<bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud> to=<username@domain.com> proto=ESMTP helo=<dhtrpdfs.outbound-mail.sendgrid.net>
Aug  1 22:34:05 ip-172-31-36-108 policyd-spf[1405044]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud;ip=208.117.61.246;r=<UNKNOWN>
Aug  1 22:34:05 ip-172-31-36-108 postfix/smtpd[1405040]: NOQUEUE: reject: RCPT from dhtrpdfs.outbound-mail.sendgrid.net[208.117.61.246]: 550 5.7.23 <username@domain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud;ip=208.117.61.246;r=<UNKNOWN>; from=<bounces+8647778-1ae0-username=domain.com@em1860.netdata.cloud> to=<username@domain.com> proto=ESMTP helo=<dhtrpdfs.outbound-mail.sendgrid.net>
```

### Expected behavior

Delivered mail

### Steps to reproduce

1.
Not sure what the person that generated the invitation did, but the invitation did not make it through postfix SPF checks.

### Desktop

Browser Version [e.g. 22]

**Comment by cakrit** [comment]
SPF TXT record updated, thank you for the catch!!!

**Comment by aathan** [comment]
Unfortunately this was not sufficient. It looks like sendgrid has additional servers to worry about:

```
Aug  2 15:08:41 ip-172-31-36-108 postfix/smtpd[1409872]: NOQUEUE: reject: RCPT from o2.w95.sendgrid.net[208.117.61.247]: 550 5.7.23 <someuser@somedomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=bounces+8647778-1ae0-someuser=somedomain.com@em1860.netdata.cloud;ip=208.117.61.247;r=<UNKNOWN>; from=<bounces+8647778-1ae0-someuser=somedomain.com@em1860.netdata.cloud> to=<someuser@somedomain.com> proto=ESMTP helo=<o2.w95.sendgrid.net>


netdata.cloud   text = "v=spf1 include:_spf.google.com include:u8647778.wl029.sendgrid.net include:em1860.netdata.cloud include:em635.discuss.netdata.cloud -all"
netdata.cloud   text = "google-site-verification=KaBi0TTsseMxn8ibgEIBBcTfQO6yx28rgyP7uMVePow"
netdata.cloud   text = "facebook-domain-verification=f31vg7nvg1ahy83fked15xlopw0wwp"

```

**Comment by cakrit** [comment]
These are public IPs that shouldn't have been in use at all. Copying here from a ticket that shouldn't have been opened internally. The TL;DR is that we just split the two IPs we have into "classes", but one of them isn't "warmed up" yet, which results in invitation emails going out from shared sendgrid IPs as well. We're reverting to using no classes, until we have a total of 3 warmed up IPs that we can split into pools.

We've recently setup and started using our `High Priority` IP Pool on SendGrid to route our invitation emails. 
As reported by some users, the SPF verification of our invitations are now failing.
Here's how the SPF fails look like:
```
Received-SPF: fail (google.com: domain of bounces+8647778-1827-bill.kalaitzis=gmail.com@em1860.netdata.cloud does not designate 208.117.53.84 as permitted sender) client-ip=208.117.53.84;
```

After some investigation, this happens due to the following:
- The `High Priority` pool only contains a single IP, which is currently in automatic warm-up mode.
- This warm-up mode will basically only route a small portion of our emails though our dedicated IP address and will slowly increase this limit in a daily basis.
- Emails that aren't routed through the dedicated IP, will be funnelled through any other IP that's part of the same pool. In our case no more IPs are available on the pool, so we fallback to the shared IPs.
- The SendGrid shared IP blocks are not whitelisted on our SendGrid domain (`em1860.netdata.cloud`), and that's what's causing the SPF check to fail. After contacting the SendGrid support, we were informed that adding an SPF whitelist for those IPs on our domain isn't supported. 

One work-around would be to include our `Normal Priority` IP (that's already warmed-up) on the `High Priority` pool as well (IPs can be part of multiple groups). Though, the support agent noted that even though this would work, it could potentially spoil the reputation of our High Priority pool as well, which is something we don't want. 

Alternatively, we were suggested to turn-off automatic warm-up and perform manual warm-up of the `High Priority` Pool.
This would mean that now all of the traffic will be routed through our our own dedicated IP (and thus SPF will work alright) and it's up to us to make sure that we don't spam the heck out of it.

To my understanding, we'll only be using our `High Priority` pool just for the invitations / sign-ins ( let's please double check this to prevent any unfortunate surprises 😄 cc @netdata/cloud-be ).
If that's the case, then the expected amount of outgoing emails is going to be quite low (looking at our daily stats on the `general` slack channel, we'd be looking at  << 4.000 mails per day) and thus any warm-up that has already taken place should be OK to prevent getting our new pool blacklisted.

**Comment by cakrit** [comment]
@vkuznecovas / @BillKalaitzis close this one when we're done please.

**Comment by BillKalaitzis** [comment]
For the time being we've merged our IP Pools, so the SPF failures are now resolved.
