### ISSUE TITLE
[Bug]: charts request fails with internal server error 500

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#538]
### Bug description

The following is consistently happening on one of my two VMs that are always online, but not on the other. 
It started in the past couple of days. The node appears online. Just can't get the response to the /charts call.

```
Request URL: https://app.netdata.cloud/api/v2/nodes/3b3d712b-e3f6-478a-976e-c339ee206e83/charts?after=-7200&before=0
Request Method: GET
Status Code: 500 
Remote Address: 44.196.50.41:443

Payload:
after: -7200
before: 0

Response:
{
    "errorMsgKey": "ErrInternal",
    "errorMessage": "Internal Server Error",
    "errorCode": "9PiHJn0xHA-48086603"
}
```

### Expected behavior

No 500

### Steps to reproduce

Check the backend to see what causes it for this node and see if the same thing happens for other nodes as well. Take it from there.

### Desktop

Browser Version [e.g. 22]

**Comment by papazach** [comment]
Apologies on the late reply on this one @cakrit.
 So there was a parent node instance (on claim_id `32b430e6-f866-469e-aa6f-5ee5ec8f4f0e`) that was queryable (but not live) and at some point became unreachable and got pruned. 
Due to hops 1 and queryability = true we were routing there the /charts request and failed, until it got pruned we routed to the hops=0 (with claim_id `f29ee27f-b5fc-4bb6-87de-8fc9669f4b75`) which works as expected.

**Comment by cakrit** [comment]
I think I understand the answer, but I'm not sure. Sounds like we have a gap in the logic, which leads us to the possibility of erroneously routing requests. So are we going to close that gap, or did I misunderstand?

**Comment by hugovalente-pm** [comment]
@papazach are we/do we need to follow-up on this? to possible check the routing logic?

**Comment by hugovalente-pm** [comment]
@papazach gentle reminder on the previous comment

**Comment by papazach** [comment]
Hello, apologies for the delayed response.
No need to follow-up on this. 
The routing logic has been greatly simplified since dropping ChartsAndDimensions streaming, additionally as we drop completely MV usage (node state is the last one remaining, all other MVs have been dropped) we'll have no such issues of obsolete information as we'll be querying the SOT directly via gRPC.

I thinkn we can safely close this one @hugovalente-pm .
