### ISSUE TITLE
[Bug]: Charts are missing `update_every` attribute on metadata.

### ISSUE THREAD

**Issue by novykh** [netdata/netdata-cloud#553]
### Bug description

The `/charts` response is missing the `update_every` attribute (granularity)

### Expected behavior

The `update_every` attribute should be returned from the `/charts` endpoint for every chart/context.

### Steps to reproduce

1. Check the response on any `/charts` request.

**Comment by hugovalente-pm** [comment]
this is causing this to happen, now both on Overview and Nodes tab (with work from @jacekkolasa )

![image](https://user-images.githubusercontent.com/82235632/186195878-67eef12b-9fa6-48e6-96f6-cf74ade194a5.png)

@juacker I guess this attribute was "lost" with the context-based initiative work. I think we will need to address this for:
* `/charts` endpoint - Overview screen
* and the _light_ version of `https://app.netdata.cloud/api/v2/spaces/<space-id>/charts/_query` - Nodes tab

**Comment by juacker** [comment]
Indeed @hugovalente-pm, this is happening for new `ctx` functionality nodes because the `update_every` parameter is not in the proto msg.

One option could be to add this parameter to the context details endpoint (`/charts/{chartID}`), currently is not there but would not be difficult to add. 
If, otherwise, this parameter is needed to be on `/charts` then, I think we would need to add them to the proto messages

**Comment by hugovalente-pm** [comment]
> One option could be to add this parameter to the context details endpoint (/charts/{chartID}), currently is not there but would not be difficult to add.

I believe this isn't ideal since it would mean having an additional call being made from the FE side

another possibility, not sure it is ok on FE, is if this comes on the `/data` payload - this would also mean a change on the /data response from the agent

@juacker we still need this on and the _light_ version of `https://app.netdata.cloud/api/v2/spaces/<space-id>/charts/_query` for the Nodes tab, is this easy?

@novykh @jacekkolasa @amalkov @ktsaou @underhood seems for the Overview scenario there may be two options:
1. this parameter is needed to be on `/charts`, so it would need to add them to the proto messages
2. add it to the `/data` payload - this would also mean a change on the `/data` response from the agent

**Comment by novykh** [comment]
My 2 cents on the matter, is that granularity is part of the chart config (doesn't change over time or by user input), hence there is no reason to put it on every `/data` request.

**Comment by juacker** [comment]
> @juacker we still need this on and the light version of https://app.netdata.cloud/api/v2/spaces/<space-id>/charts/_query for the Nodes tab, is this easy?

@hugovalente-pm Adding `update_every` to `/_query` response could be added without changing anything in the proto/agent, but looking at the previous DB query I think we were not returning it old CnD proto nodes either. Should we add it to`/_query` in any case?

**Comment by juacker** [comment]
I'm testing adding it on `/_query` response and it does not seem to solve the issue:

![image](https://user-images.githubusercontent.com/2930882/186456902-9d2f8a0a-d214-43db-b1e3-5043ed22bd5c.png)

So I guess it's only needed on `/charts`

**Comment by hugovalente-pm** [comment]
@jacekkolasa for the Nodes tab can you see what is missing after @juacker 's work to add this?
not sure something is needed on FE

**Comment by papazach** [comment]
So it seems that after all, `update_every` should be included to the proto definition.

Given that: 
1. Performing an additional HTTP call (aka context details) to fetch this in real-time is not worth the latency and data transfer
2. Adding this to the /data response, will again make it accessible to only a specific agent version and onwards (similar to adding it to the proto definition). Plus it might not make much sense semantically.

For the record, during the protos definitions sessions the question about including`update_every` field was [brought up](https://github.com/netdata/cloud-backend/issues/261#issuecomment-1171350455) for discussion - mainly with regard to the retention updates - but we did not opt to include it in the payloads.

**Comment by hugovalente-pm** [comment]
> after all, update_every should be included to the proto definition.

Yes.

> For the record, during the protos definitions sessions the question about includingupdate_every field was https://github.com/netdata/cloud-backend/issues/261#issuecomment-1171350455 for discussion - mainly with regard to the retention updates - but we did not opt to include it in the payloads.

I remember the question, but I didn't recall that it was being used to display some info on the tooltip at that time

I believe we need to add it to the the proto messages, since adding to the `/data` doesn't make much sense.

**Comment by jacekkolasa** [comment]
Regarding Nodes View and `/_query` payload, if we'll have camelized `updateEvery`, granularity should show up correctly.

@juacker Can we use `updateEvery` (similarly as camelCase is used in `rooms/${roomID}/charts`), or you prefer FE to respect `update_every`?

**Comment by papazach** [comment]
> I remember the question, but I didn't recall that it was being used to display some info on the tooltip at that time

Yeap me neither, I think that we all lost this. I will create the related tickets/tasks for the BE.

PS: That could have been something that a front-end team member _could_ have caught. Don't want to rant about this at all, just want to mention it, since back then I had to elaborate about the inclusion of FE on the design phase.

**Comment by juacker** [comment]
> Regarding Nodes View and `/_query` payload, if we'll have camelized `updateEvery`, granularity should show up correctly.
> 
> @juacker Can we use `updateEvery` (similarly as camelCase is used in `rooms/${roomID}/charts`), or you prefer FE to respect `update_every`?

yes, of course @jacekkolasa, good catch!

**Comment by papazach** [comment]
x-referencing here the set of tasks that are needed to be completed in order to include `update_every` in the Overview `/charts` response:
https://github.com/netdata/cloud-backend/issues/336

**Comment by juacker** [comment]
renamed to `updateEvery` on `/_query` @jacekkolasa:

![image](https://user-images.githubusercontent.com/2930882/187645351-fe392f6a-be2a-4cc0-ade6-41b6ec27dd5c.png)

**Comment by hugovalente-pm** [comment]
> My 2 cents on the matter, is that granularity is part of the chart config (doesn't change over time or by user input), hence there is no reason to put it on every /data request.

@novykh on a conversation with @amalkov @ktsaou @papazach @ralphm this was discussed and since the granularity will be related to the data retrieved (considering potential chart label filtering, etc.) it makes more sense for this to be exposed on the `/data` request response.

let us know if you see any other reason why it should not be there.

**Comment by novykh** [comment]
No it's fine, although you know that it doesn't change right? In any case we can make the change on the frontend to be ready for this.

**Comment by hugovalente-pm** [comment]
> although you know that it doesn't change right?

from what I understood it can, let's say you 3 nodes where 2 have a given `update_every` and the last another with smaller frequency, when getting `/data` from all you get the highest `update_every` but if you filter the chart for data from the one with the smaller frequency you get that

@ktsaou @papazach let's proceed with pushing this to the `/data` request starting from the Agent

**Comment by novykh** [comment]
If that is possible, then makes total sense.

**Comment by papazach** [comment]
The BE change is deployed to all ENVs and things seem now ok.

<img width="1142" alt="Screenshot 2022-09-09 at 2 19 11 PM" src="https://user-images.githubusercontent.com/8328670/189338953-debfdd0d-5ff7-4594-9e4b-372a18651635.png">

Feel free to check/validate and close the ticket 👍🏼 
cc @hugovalente-pm @novykh

**Comment by novykh** [comment]
Cool thanks, I will release the frontend part of it later today as well.

**Comment by jacekkolasa** [comment]
@novykh `netdata/charts v0.5.41` are already on production, i think your change is there

**Comment by hugovalente-pm** [comment]
this is on PROD and done 💪
