### ISSUE TITLE
[Bug]: Broken links to alert documentation

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#631]
### Bug description

The k8s* alerts shown below don't have corresponding articles in https://community.netdata.cloud/c/alerts/28
As a result, the links to "learn more about this alert" such as https://community.netdata.cloud/t/k8s-cgroup-ram-in-use are broken

<img width="327" alt="image" src="https://user-images.githubusercontent.com/43294513/198345545-b0f155d9-c5f0-4e4d-a163-4222c01c26ae.png">

### Expected behavior

No broken links, ever.

We need an automated mechanism to:
 - Prevent a broken link from ever being presented. Remember that users may define their own alerts, so this must be done on the cloud side. This will prevent the poor UX. 
 - Notify the documentation team every time a new, undocumented alert is created appears (I believe we need this automation on the agent side. The use cases team can help here). This isn't required for the bug to be closed, so we'll track it in [the agent](https://github.com/netdata/netdata/issues/13901)

### Steps to reproduce

1. Click on one such alert

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
to check on priority for this @cakrit do we have an idea of how many occurrences we have?

**Comment by tkatsoulas** [comment]
@hugovalente-pm They piled up because as I said in the past we didn't create a lifecycle process for this project

<pre>Cloned the master branch from netdata repo (owner: netdata)
Found  250  alerts, checking if guides exists into the community forum
Checking for link https://community.netdata.cloud/t/adaptec-raid-ld-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/anomalies-anomaly-probabilities. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/adaptec-raid-pd-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/apcupsd-10min-ups-load. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/apcupsd-ups-charge. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/anomalies-anomaly-flags. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/bcache-cache-dirty. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/apcupsd-last-collected-secs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/bcache-cache-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/beanstalk-server-buried-jobs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/bind-rndc-stats-file-size. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/boinc-compute-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/boinc-active-tasks. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/boinc-upload-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/boinc-total-tasks. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/btrfs-metadata. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/btrfs-allocated. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/btrfs-data. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cgroup-10min-cpu-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/btrfs-system. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ceph-cluster-space-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cgroup-ram-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cgroup-10s-received-packets-storm. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/k8s-cgroup-10min-cpu-usage. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/k8s-cgroup-ram-in-use. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/cockroachdb-used-storage-capacity. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/k8s-cgroup-10s-received-packets-storm. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/cockroachdb-used-usable-storage-capacity. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cockroachdb-underreplicated-ranges. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cockroachdb-open-file-descriptors-limit. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-cpu-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/20min-steal-cpu. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-cpu-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-dbengine-global-fs-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-dbengine-global-io-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-dbengine-global-flushing-warnings. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-dbengine-global-flushing-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/disk-space-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/disk-inode-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-disk-utilization. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-disk-backlog. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/dns-query-query-status. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/dnsmasq-dhcp-dhcp-range-utilization. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/docker-unhealthy-containers. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/lowest-entropy. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/exporting-last-buffering. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/exporting-metrics-sent. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-cpu-iowait. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/fping-last-collected-secs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/cockroachdb-unavailable-ranges. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/fping-host-reachable. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/fping-host-latency. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/fping-packet-loss. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/go-d-job-last-collected-secs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/gearman-workers-queued. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/haproxy-backend-server-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/haproxy-backend-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/hdfs-capacity-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/hdfs-missing-blocks. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/hdfs-stale-nodes. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/hdfs-dead-nodes. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/hdfs-num-failed-volumes. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/httpcheck-web-service-bad-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/httpcheck-web-service-bad-content. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/httpcheck-web-service-unreachable. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ioping-disk-latency. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/httpcheck-web-service-slow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/semaphores-used. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/semaphore-arrays-used. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ipfs-datastore-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-node-config-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-token-requests. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-operations-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ipmi-sensors-states. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-10s-pleg-relist-latency-quantile-05. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-10s-pleg-relist-latency-quantile-09. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/kubelet-10s-pleg-relist-latency-quantile-099. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/linux-power-supply-capacity. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ipmi-events. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/load-average-15. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/load-average-5. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/load-average-1. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mdstat-last-collected. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mdstat-disks. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mdstat-mismatch-cnt. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mdstat-nonredundant-last-collected. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/megacli-adapter-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/megacli-pd-predictive-failures. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/megacli-pd-media-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/megacli-bbu-relative-charge. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/megacli-bbu-cycle-count. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1hour-ecc-memory-correctable. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1hour-ecc-memory-uncorrectable. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1hour-memory-hw-corrupted. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-10s-slow-queries. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-10s-waited-locks-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/memcached-cache-memory-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/memcached-out-of-cache-space-time. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-connections. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-replication. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-replication-lag. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-galera-cluster-size. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-galera-cluster-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/mysql-galera-cluster-state-warn. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/mysql-galera-cluster-state-crit. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/1m-received-traffic-overflow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-sent-traffic-overflow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/inbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/outbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wifi-inbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wifi-outbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/interface-inbound-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/interface-outbound-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-fifo-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10s-received-packets-storm. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/netfilter-conntrack-full. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/nut-10min-ups-load. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/nut-ups-charge. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/nut-last-collected-secs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/pihole-blocklist-last-update. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ping-host-reachable. <font color="#F66151">Could not connect to the server</font>
Checking for link https://community.netdata.cloud/t/ping-host-latency. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/ping-packet-loss. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/portcheck-connection-timeouts. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/portcheck-connection-fails. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/pihole-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/postgres-acquired-locks-utilization. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-total-connection-utilization. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-txid-exhaustion-perc. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-db-transactions-rollback-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-db-cache-io-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-db-deadlocks-rate. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-cache-io-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-index-cache-io-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-toast-cache-io-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-bloat-size-perc. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-toast-index-cache-io-ratio. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-last-autovacuum-time. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-index-bloat-size-perc. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/postgres-table-last-autoanalyze-time. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/active-processes. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ram-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/python-d-job-last-collected-secs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ram-available. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/oom-kill. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ram-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/ram-available. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/redis-bgsave-broken. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/redis-bgsave-slow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/redis-connections-rejected. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/retroshare-dht-working. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/riakkv-list-keys-active. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/redis-master-link-down. <font color="#E9AD0C">Link not found, status code: 404</font>
Checking for link https://community.netdata.cloud/t/riakkv-kv-get-slow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/riakkv-kv-put-slow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/riakkv-vm-high-process-count. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/scaleio-storage-pool-capacity-utilization. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/scaleio-sdc-mdm-connection-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1min-netdev-backlog-exceeded. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1min-netdev-budget-ran-outs. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10min-netisr-backlog-exceeded. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/30min-ram-swapped-out. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/used-swap. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/sync-freq. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-service-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-socket-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-path-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-device-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-mount-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-automount-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-target-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-swap-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-scope-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/systemd-slice-unit-failed-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/tcp-connections. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-tcp-accept-queue-overflows. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-tcp-accept-queue-drops. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-tcp-syn-queue-drops. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-tcp-syn-queue-cookies. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/tcp-memory. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/tcp-orphans. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10s-ipv4-tcp-resets-sent. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/10s-ipv4-tcp-resets-received. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/system-clock-sync-state. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-ipv4-udp-receive-buffer-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/1m-ipv4-udp-send-buffer-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/unbound-request-list-overwritten. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/unbound-request-list-dropped. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-system-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-mem-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-storage-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-swap-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-load-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-database-storage-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-applmgmt-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vcsa-software-updates-health. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-socket-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-queue-message-drop. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-queue-message-expired. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-queue-message-unhandled. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-average-scheduler-utilization. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-cluster-dropped. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-disconnect-received-reason-not-normal. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-connack-sent-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-netsplits. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-disconnect-sent-reason-not-normal. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-subscribe-auth-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-publish-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-subscribe-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-unsubscribe-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-puback-sent-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-publish-auth-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-puback-received-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-puback-unexpected. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubrec-received-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubrec-invalid-error. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubrel-received-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubrec-sent-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubrel-sent-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubcomp-received-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubcomp-unexpected. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vernemq-mqtt-pubcomp-sent-reason-unsuccessful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-vm-mem-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-host-mem-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-inbound-packets-errors-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-outbound-packets-errors-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-cpu-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-inbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/vsphere-outbound-packets-dropped-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-1m-unmatched. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-1m-successful. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-1m-redirects. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-1m-bad-requests. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-1m-internal-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-web-slow. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/web-log-5m-requests-ratio. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/whoisquery-days-until-expiration. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-10min-cpu-usage. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-swap-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-outbound-packets-discarded. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-inbound-packets-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-outbound-packets-errors. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-inbound-packets-discarded. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-ram-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/wmi-disk-in-use. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/x509check-days-until-expiration. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/x509check-revocation-status. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/zfs-memory-throttle. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/zfs-pool-state-warn. <font color="#33DA7A"> OK </font>
Checking for link https://community.netdata.cloud/t/zfs-pool-state-crit. <font color="#33DA7A"> OK </font>
Try to clean up the folder:  temp-folder
<font color="#33DA7A">Done</font>
SUMMARY
Found 26 guides with broken links 
Here is a list of them:
cgroup_10s_received_packets_storm	404
k8s_cgroup_10min_cpu_usage	404
k8s_cgroup_ram_in_use	404
k8s_cgroup_10s_received_packets_storm	404
dns_query_query_status	404
mysql_galera_cluster_state_warn	404
mysql_galera_cluster_state_crit	404
ping_host_reachable	404
ping_host_latency	404
ping_packet_loss	404
postgres_acquired_locks_utilization	404
postgres_total_connection_utilization	404
postgres_txid_exhaustion_perc	404
postgres_db_transactions_rollback_ratio	404
postgres_db_cache_io_ratio	404
postgres_db_deadlocks_rate	404
postgres_table_cache_io_ratio	404
postgres_table_index_cache_io_ratio	404
postgres_table_toast_cache_io_ratio	404
postgres_table_bloat_size_perc	404
postgres_table_toast_index_cache_io_ratio	404
postgres_table_last_autovacuum_time	404
postgres_index_bloat_size_perc	404
postgres_table_last_autoanalyze_time	404
redis_connections_rejected	404
redis_master_link_down	404
</pre>

Could you please cooperate with Foti so we could add some bare minimum info for the missing alerts, with a placeholder that this is a WIP?

**Comment by andrewm4894** [comment]
I'll have a look to see if, within discourse customizatios, we can fire custom events to PH when the 404 page is triggered same way we do for blog and learn. That way we'd be able to triage based on traffic to them.

**Comment by andrewm4894** [comment]
Added this to body in community and seems to work. 

![image](https://user-images.githubusercontent.com/2178292/199479229-a07cb62b-b05e-49a0-95d6-76f063fd42ae.png)

Created report of all page-not-found events by url. We can let this get traffic for a few days and maybe then start using it to help spot parts of sites getting actual traffic that are tiggering page-not-found events.

**Comment by novykh** [comment]
Fixed with disabled link.
