### ISSUE TITLE
[Bug]: Cleared alerts don't show correct info

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#705]
### Bug description

As mentioned at the end of https://github.com/netdata/netdata-cloud/issues/656 , when clicking on an alert notification to see the details of an alert, you now see a page, but the chart says "something went wrong". I expect it has to do with the `null` node id shown in the screenshot below.

### Expected behavior

Show the live chart. 

### Steps to reproduce

1. Click on a notification of a currently clear alert

### Screenshots

![image](https://user-images.githubusercontent.com/43294513/212930814-3567c414-0c21-427b-aabb-4d8256508c2d.png)

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@cakrit do you recall if this happens when the node is no longer available to be queried (when it is Offline)? was trying to find a case were this happens and going to an old a alert I get
![image](https://user-images.githubusercontent.com/82235632/235118031-067dffed-4797-4b05-bec1-923e59dc4e27.png)

**Comment by hugovalente-pm** [comment]
this is fixed
![image](https://github.com/netdata/netdata-cloud/assets/82235632/b3bed339-ed6a-4087-a8b3-4a04fccb833c)
