### ISSUE TITLE
[Bug]: help messages in full screen view of panels prevent from making changes

### ISSUE THREAD

**Issue by iorvd** [netdata/netdata-cloud#712]
### Bug description

If you go to a full-screen view of any panel, and will try to change some of its values, the help message will try to prevent you from making changes and the cursor will be blinking fast (firefox)

### Expected behavior

I can easily change the values in the dropdown menu

### Steps to reproduce

1. Go to an arbitrary panel of your choice
2. Click `Full screen` button
3. Try to change the aggregation values of the panel

### Screenshots

https://user-images.githubusercontent.com/93676586/214570068-0dce7e9e-748e-40ac-8b9c-531de820ba27.mp4

### Desktop

OS: macOS 13.1
Browser: Firefox
Browser Version: 109.0

**Comment by jacekkolasa** [comment]
This happens, because tooltip is trying to position itself above the dropdown. But there is not enough space, and goes on top of the dropdown button, which causes flickering.

@hugovalente-pm @christophidesp @novykh in this case I suggest that if:
- tooltip is set to `align: top`, AND
- we won't have space for tooltip above the trigger, AND
- we have space below the trigger,
we'll display it below.

Alternatively, we could have new align: "auto" positioning, which will display `below` when trigger is in top part of the screen, and `above` when trigger is in bottom part of the screen.

WDYT?

**Comment by jacekkolasa** [comment]
As we discussed with @hugovalente-pm , we'll have the tooltip switch placement only when there's not enough space for it above the trigger element

**Comment by jacekkolasa** [comment]
fix is on production
