### ISSUE TITLE
[Bug]: Per CPU utilization charts are broken

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#718]
### Bug description

Under CPUs, try to work with the new "cpu" label. 
On our prod space in the k8s-prd room, this get. 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/43294513/216658536-c935a114-ff4f-4bb0-abed-8ba3b8e8beec.png">
- X axis is wrong, ends at 100%, but the values are at 600%
- All the values are on top of each other, so in fact I can only see one of the cores at a time
- I seriously doubt that so many cores are constantly at 100% each

Clicking to see just one of the cpus makes it even worse. See how the units  decided to get really precise. I believe this is has been reported before too, but in percentages it should be really trivial to lock the precision.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/43294513/216659320-52993c32-c915-48fe-93df-5b046a5f8f88.png">

### Expected behavior

useable charts

### Steps to reproduce

1. Visit the UI and select group by cpu in the CPUs > Utilization

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
> X axis is wrong, ends at 100%, but the values are at 600%
> All the values are on top of each other, so in fact I can only see one of the cores at a time

I believe this is like this because CPU charts are set statically to be always showing at 100% y-scale, we have an issue that this scale isn't respected on custom dashboards and you can see it goes to around 20,000% 
![image](https://user-images.githubusercontent.com/82235632/223463749-d62c761e-d166-472b-b489-71ceabcff8d3.png)

> I seriously doubt that so many cores are constantly at 100% each

if filter the chart for one node it is in fact the data we are getting back on the request
![image](https://user-images.githubusercontent.com/82235632/223465062-10c0d15b-69f2-42df-9bba-787aaff6dd1b.png)

while looking to the data of this same node on the parent dashboard we don't see these reported values

![image](https://user-images.githubusercontent.com/82235632/223465682-15151cee-624d-4217-ad93-dbc068ebc1aa.png)

this value of 100% comes only when you group by CPU (it also happens if you on instance if you group by CPU before) it seems FE is asking for ALL the dimensions on this case hence the 100%

https://user-images.githubusercontent.com/82235632/223468971-a92dc1c9-1823-45af-8f12-a3f62ddf6079.mp4

so the multiple issues to fix seem to be:
- [ ] don't send all the dimensions when group by `cpu`, probably don't send anything like the other cases
- [ ] fix the precision on these percentage representations

**Comment by burbuli8ra** [comment]
Released on [v5.14.0](https://github.com/netdata/cloud-frontend/releases/tag/5.14.0)
