### ISSUE TITLE
[Feat]: Simplify and guide the connect nodes journey

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#745]
### Problem

With recent additions the connect nodes page is "too busy" and the cognitive load on users is higher. 

## Goal

Ensure users have a clear and guided journey when they are onboard on Netdata Cloud

### Description

Current landing page, and more specifically the connect nodes component, has some issues:
- This view feels too busy/noisy now, there's a lot of text for the user to read through and visual elements to grasp before reaching the button that copies the kickstart command. 
- The copy button is more highlighted (visible) on the claim token box, instead of the kickstart box. should be the other way around.
- The claim token and room token are too prominently displayed, and duplicates the hex strings unnecessarily. Just replace with buttons dedicated to copy without printing the hex again.

We should aim to have a clearer onboarding page for someone that signs-up to Netdata Cloud like a splash screen or wizard with steps for what we want them to achieve 
* One step, Connect your systems or infrastructure or something similar, where we present the systems users can run Netdata on: Multiple Linux distros, Docker, Kubernetes, MacOS, Windows, etc.
* The following steps are optional:
   * Connect more nodes
   * Configure integrations
   * Invite teammate
   * Go to app

We still need to provide them with prominent links or CTAs to
* Check the demo envirornment
* Check possible deployment strategies

We still need to work on simplifying the current connect node component to remove some noise since it will still be needed to add more nodes.

### Importance

really want

### Value proposition

1. Make the user experience of connecting new nodes simpler and easier.

### Proposed implementation

TBD

**Comment by andrewm4894** [comment]
related internal slack that touches on some of this: https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1680006996243789

**Comment by hugovalente-pm** [comment]
@christophidesp @sashwathn @shyamvalsan repurposing this ticket for what we discussed:
* we should aim to have a clearer onboarding page for someone that signs-up to Netdata Cloud, the discussion lead to a splash screen with steps for what we want them to achieve -- in future this can be used to properly onboard user coming from different journeys (from Agent, invitation, URL shared, etc.)
   * One step, Connect your systems or infrastructure or something similar, where we present the systems users can run Netdata on: Multiple Linux distros, Docker, Kubernetes, MacOS, Windows, etc.
   * Another step, present them the demo enviornment
* we also should work on simplifying the current onboard screen, as mentioned on this ticket, to remove some noise

**Comment by hugovalente-pm** [comment]
_Original report_

### Problem

With recent additions the connect nodes page is "too busy" and the cognitive load on users is higher. 

The original page was simple and to the point, to connect new nodes copy this command and run it on your system. 

### Description

![image](https://user-images.githubusercontent.com/24860547/221577331-733a26fc-823a-4e65-92de-c555fa2a7b29.png)

- This view feels too busy/noisy now, there's a lot of text for the user to read through and visual elements to grasp before reaching the button that copies the kickstart command. 

- The copy button is more highlighted (visible) on the claim token box, instead of the kickstart box. should be the other way around.
 
- There's an indentation gap between "Check out documentation" and "Claim token", which should be fixed. 
 
- The claim token and room token are too prominently displayed, and duplicates the hex strings unnecessarily. Just replace with buttons dedicated to copy without printing the hex again.

### Importance

really want

### Value proposition

1. Make the user experience of connecting new nodes simpler and easier.


### Proposed implementation

![image](https://user-images.githubusercontent.com/24860547/221577662-ad665060-482d-4747-984c-ff097287e22e.png)

Suggestions:
- Move nightly and stable to a simplified button option (with tooltips showing the text, instead of a doc link so user can stay in-app and make a decision)
- The claim and room token should be present but be minimized so there's just "copy claim token" "copy room token" buttons without having to print the hex string again.

**Comment by hugovalente-pm** [comment]
@christophidesp on the first step to display the available environments we should provide the following list:
* Debian
* Ubuntu
* CentOS
* Fedora
* SUSE
* Amazon Linux
* Red Hat Enterprise Linux
* Oracle Linux
* Alpine Linux
* Alma Linux
* Arch Linux
* Manjaro Linux
* Docker
* Kubernetes
* MacOS
* Windows

**Comment by hugovalente-pm** [comment]
for all the linux based ones the instructions will be this
![image](https://github.com/netdata/netdata-cloud/assets/82235632/f9ddd3a2-bac4-4a5f-b3bb-32403848705c)

for Docker:
![image](https://github.com/netdata/netdata-cloud/assets/82235632/7c83445d-a885-414c-b93d-bf3a46b00be4)

Kubernetes:
![image](https://github.com/netdata/netdata-cloud/assets/82235632/029d5c59-2d83-481c-887e-a06917f4ec82)

MacOS:
![image](https://github.com/netdata/netdata-cloud/assets/82235632/70e97dd2-01ad-4681-9712-de0f2d56362a)

Windows:
1. Install [Windows Exporter](https://github.com/prometheus-community/windows_exporter) on every Windows host you want to monitor.
2. Install Netdata agent on Linux, FreeBSD or Mac.
3. Configure Netdata to collect data remotely from your Windows hosts by adding one job per host to windows.conf file. See the [configuration section](https://learn.netdata.cloud/docs/data-collection/monitor-anything/System%20Metrics/Windows-machines#configuration) for details.
4. Enable virtual nodes configuration so the windows nodes are displayed as separate nodes.

Source: https://github.com/netdata/netdata-cloud/issues/815

**Comment by hugovalente-pm** [comment]
as per a conversation with @novykh the suggestion is to not take out the "space sidebar: with the rooms, etc." since it will become less complex managing the code due to multiple conditionals (see below what we mean)

for new users we should show it collapsed but it should be available

@kapantzak goal is to have less conditionals around the other existing components

cc/ @christophidesp 

slack thread: https://netdata-cloud.slack.com/archives/C01FK384DB5/p1689781813783979?thread_ts=1689781109.485709&cid=C01FK384DB5

![image](https://github.com/netdata/netdata-cloud/assets/82235632/2a36d598-eadd-492c-9987-3451560b53cc)

**Comment by hugovalente-pm** [comment]
this is done with the onboarding wizard

![image](https://github.com/netdata/netdata-cloud/assets/82235632/24dd011f-e391-431d-8b91-55e454134b67)
