### ISSUE TITLE
[Bug]: reset button hidden behind menu when i select percentile

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#763]
### Bug description

the reset button seems to be hidden behind the menu for me when i select percentile

<img width="952" alt="image" src="https://user-images.githubusercontent.com/2178292/224512065-d0f9462a-921c-4652-8d33-88b74923f94c.png">

### Expected behavior

should maybe not be hidden, although space is a bit tight idk.

### Steps to reproduce

1. use percentile options in chart menu
2. see if you can press the reset button once rhs menu is expanded

### Desktop

Browser Version [e.g. 22]

**Comment by andrewm4894** [comment]
a very minor bug imo, maybe even not a bug?

**Comment by hugovalente-pm** [comment]
I think this is definetily a bug, low prio one since it depends on screen resolution.
the composite chart bar is scrollable but this is not evident. I'm not sure if new charts will deal with something like this so probably better ping @christophidesp and @novykh 

https://user-images.githubusercontent.com/82235632/235113779-7e02dee0-0093-4927-b5ab-df8977a4e39e.mp4
