### ISSUE TITLE
Unable to Change "using" from "sum of ABS" 

### ISSUE THREAD

**Issue by donCarlosOne** [netdata/netdata-cloud#778]
### Bug description

I've created a custom dashboard to monitor CPU (and other metrics) from 4 different servers.  When I change the grouping from dimension to node (or instance), the chart displays an aggregate sum of the 4 servers (400% rather than 100% as the max value) whereas the Overview page displays this correctly with 100% as the max value.

### Expected behavior

It should display the same values in both the dashboard and the overview.

### Steps to reproduce

1.  Create a new custom dashboard
2. Add the cpu.percentage chart (or any chart)
3. Save and view the dashboard
4. Change the grouping from dimension to node or instance

### Screenshots

Overview screen chart displaying correctly

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/2841617/227704430-501567db-c27d-4937-b035-7eee9a2d9e5c.png">

Dashboard chart after changing group by to node:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/2841617/227704609-a768685f-89d5-4ac5-913d-c8d2ff73e600.png">

### Desktop

OS: MacOS 13.2.1
Browser Edge
Browser Version latest

### Additional context

It's not useful to see the aggregate sum of the 4 servers' CPUs, rather it is more important to see individual CPU values that I can in the Overview screen - and then It seems the only way to see the individual CPUs at a glance is to save a custom dashboard.  Having to change the grouping from dimension to node every time the Overview screen is loaded (for EVERY metric on the screen) is extremely tedious.  While the workaround to create a dashboard is useful, even that itself is tedious as each metric must be manually added to the dashboard - end then doesn't display the equivalent of the Overview screen anyway.

**Comment by hugovalente-pm** [comment]
@donCarlosOne sorry for taking so long to pick this one up, somehow got lost.

> whereas the Overview page displays this correctly with 100% as the max value.

The fact is that on the Overview we have the CPU chart y-axis with a fixed limit to 100% and this limit isn't being applied on the custom dashboards. I tried to show this in a very rough way to compare
![image](https://user-images.githubusercontent.com/82235632/235111091-69c2af4d-cc16-4696-a7b1-df7079e8983a.png)

If you sum the individual percentages of each node you will see that you get more than the 100% total
![image](https://user-images.githubusercontent.com/82235632/235111191-c69cc3d9-a3eb-4703-ae0f-48fbb22873d1.png)

This chart shows more than 100% because it is a stacked chart so if you change it to a line chart, for example, you get the proper individual node CPU value series without them being "stacked".
![image](https://user-images.githubusercontent.com/82235632/235111549-a3415860-0bef-4a72-bbbc-e41a42342e2e.png)

> Having to change the grouping from dimension to node every time the Overview screen is loaded (for EVERY metric on the screen) is extremely tedious. 

This is true and we are planning to solve this, there is already a feature request tracking this need https://github.com/netdata/netdata-cloud/issues/789

> While the workaround to create a dashboard is useful, even that itself is tedious as each metric must be manually added to the dashboard - end then doesn't display the equivalent of the Overview screen anyway.

@ktsaou @novykh this hard limit on CPU charts as 100% shouldn't be restricted on the Overview screen if the data displayed there is above that.
is there any concern on removing this limit on these cases where it goes above?

**Comment by hugovalente-pm** [comment]
actually my last question is covered on this one https://github.com/netdata/netdata-cloud/issues/774
so will close this bug @donCarlosOne
