### ISSUE TITLE
[Bug]: Using 'silent' in .conf file doesn't remove it from Netdata Cloud 

### ISSUE THREAD

**Issue by todoneunl** [netdata/netdata-cloud#786]
### Bug description

When I change the `to:` value from `sysadmin` to `silent` for (in this case) `elasticsearch_cluster_health_status_yellow` in `health.d/elasticsearch.conf` (see first screenshot), it still gives an active alert (warning) in Netdata Cloud (see second screenshot). 

I did `netdatacli reload-health` and also `systemctl restart netstat` (to be sure).

Running the most recent netstat version on an up-to-date Debian 11.

### Expected behavior

When a `to:` value is changed in a configuration file from `sysadmin` to `silent`, it should not send any alerts and not showing any alerts. Or it should at least have a remove option in Netdata Cloud.

### Steps to reproduce

See bug description.

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/41594439/229471654-5ebfa841-ed0f-452d-8dfe-f6cc18402de4.png)

![Schermafdruk van 2023-04-03 11-39-04](https://user-images.githubusercontent.com/41594439/229472789-7c83bf9f-dadd-4dd2-922d-0d7c5b212168.png)

### Desktop

OS: Ubuntu Linux 22.04
Browser: Firefox
Browser Version: 111

**Comment by hugovalente-pm** [comment]
@MrZammler @car12o could you check on the expected behaviour of this? 
not sure this one https://github.com/netdata/netdata-cloud/issues/330 could have some interference on this

**Comment by hugovalente-pm** [comment]
@joenepraat we touched upon this on the daily call and the behaviour that you see is as expected, since the silencing of an alert is:
> Silence alarm notifications. Alarm conditions will be evaluated, the alarms will appear in the log and the Netdata UI will show the alarms as active, but no notifications will be sent.

this means that the alert status changes is triggered and it is sent to Cloud, what won't happen is the sending of any notificaitons.

is your goal to completely disable the alert?
> Disable health checks completely. Alarm conditions will not be evaluated at all and no entries will be added to the alarm log.

if yes, then you can achieve it with either:
* https://learn.netdata.cloud/docs/alerts-and-notifications/configure-alerts#disable-some-alerts
* https://learn.netdata.cloud/docs/alerts-and-notifications/health-api-calls#health-management-api

**Comment by todoneunl** [comment]
@hugovalente-pm Thanks for your reply. This was not very clear to me first, so sorry for the extra work.

I commented out the whole section of `elasticsearch_cluster_health_status_yellow` (I guessed that's the same as definition) and now I don't see the alerts anymore. Thanks!
