### ISSUE TITLE
[Feat]: ability to save/override chart defaults in a Space or Room

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#789]
### Problem

I would like to use a different default chart visualization than the default NC one. 

For example instead of it being this each time:

![image](https://user-images.githubusercontent.com/2178292/230334738-43e1f396-1241-4090-8042-c3e4d6619c81.png)

i would rather the default be something like this:

![image](https://user-images.githubusercontent.com/2178292/230334822-cf06e6f8-d12c-4eda-aa84-d332bbd73289.png)

### Description

I would like to select any combination of actions on the chart and next to the "Reset" button have some way to "Set as Default" or "Save" for that chart in that room (or maybe for that particular user too although that's debatable). 

Besides the existing configurations of chart type, filter selections, aggregation functions, etc. it should be possible to customize chart y-axis min and max values

```[tasklist]
### Related tickets
- [ ] This one
- [ ] https://github.com/netdata/netdata-cloud/issues/551
- [ ] https://github.com/netdata/product/issues/3027 --> main prio https://github.com/netdata/product/issues/2370 (mentioned above)
- [ ] https://github.com/netdata/netdata-cloud/issues/579
```

### Importance

really want

### Value proposition

1. save me having to do save set of manual actions each time i go to a space.
2. give me more flexibility and customization options.

### Proposed implementation

Have cloud or the browser even, be able to save and remember the custom defaults for each room.

**Comment by andrewm4894** [comment]
Bonus points maybe if this config could actually be saved by me as users as "my saved view" that applies to all charts in the space and i can easily just switch between them. 

E.g sometimes depending on what "mode" im in - i might want two completely different sets of defaults to just apply - so would be cool if i could save these as "views" or something and easily jump into them.

**Comment by luisj1983** [comment]
+1 or +1million
really blocks troubleshooting workflows.
might be worth making the views sharable.

**Comment by aldem** [comment]
My 2ct: all settings which could be changed in dashboard by clicking should be configurable as defaults (per context), without cloud, so the whole picture is in "proper" state when the dashboard is opened on any fresh browser (which may have no connection to the Internet at all).

**Comment by hugovalente-pm** [comment]
this is done

**Comment by nethershaw** [comment]
> this is done

No it isn't. Where do these get saved to? Where do you list them? How do you recall one you've already saved to apply it to a chart? How do you edit one you've already saved? What happens if you try to use that button on a Netdata node's local dashboard instead of the cloud dashboard? Where is the documentation for this feature?

**Comment by andrewm4894** [comment]
@Ancairon any idea on this one?

**Comment by Ancairon** [comment]
:wave: Hey guys :point_down: 

[This](https://learn.netdata.cloud/docs/dashboards-and-charts/netdata-charts#title-bar) is the section of our docs covering it.

For 
>Where do these get saved to? Where do you list them?

I would @netdata/cloud-fe as I don't know the specific details.

> How do you recall one you've already saved to apply it to a chart?

You go to the chart, click on "User settings" in the Title Bar and select the setting you have previously saved.

> How do you edit one you've already saved?

There are tooltips everywhere
![image](https://github.com/user-attachments/assets/7f0e7332-cdd4-4a6c-a20e-22305a30c537)


>What happens if you try to use that button on a Netdata node's local dashboard instead of the cloud dashboard?

I have reported this internally, currently it seems that the user configuration on the Agent dashboard has a bug and is not able to be saved.

> Where is the documentation for this feature?

given the size of the team and the rapid changes, we generally try to explain in depth things that do not have visual cues or tooltips, otherwise our docs would've been full of explaining everything and it is not really scalable. For this feature we settled for a mention in the docs and the front-end team added tooltips in every step of the way on the UI.


Let me know if you got any more questions.
