### ISSUE TITLE
[Bug]: Unable to add a specific chart from a single existing node to a dashboard

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata-cloud#798]
### Bug description

When we add a graphic in a dashboard, we can select a single node and supposedly select one of its particular data.
For instance disk.md3 is no longer available, even though the dashboard shows such a graphic already for the selected node!

Furthermore, selecting a single node to display used to show the node name on the graphics allowing to compare at a glance various node on the same data.

Also, it's no longer possible to select disk.io for disk.md127 or disk.md3 which are shown on screenshots !?

### Expected behavior

Obtaining the node's specific data in the drop down.

### Steps to reproduce

1. Open a dashboard
2. Add chart
3. Select a single node
4. Search for disk.io for one of the HD (md3 for example), it's not there
5. Add the disk.io chart, single node selected however chart title is blank failing to identify the node in question to compare with others

### Screenshots

Below screenshots shows old charts at top, while new charts at bottom with blank title, not identifying actual node:

![image](https://user-images.githubusercontent.com/104206200/233994779-d1544b8a-5919-495c-b163-c892cc55a91e.png)

Below screenshot shows trying to find the disk.md3 data on an existing node, there is none in drop-down even though a chart already exists for that md3 data:
![image](https://user-images.githubusercontent.com/104206200/233995060-14f59faf-2090-4802-bfbd-983ba3261e15.png)

### Desktop

OS: Windows 11	
Browser: Chrome, latest version

**Comment by hugovalente-pm** [comment]
This is introduced when we removed the single specific chart and now we have context based charts everywhere.

> For instance disk.md3 is no longer available, even though the dashboard shows such a graphic already for the selected node!
> Also, it's no longer possible to select disk.io for disk.md127 or disk.md3 which are shown on screenshots !?

You should be able to achieve this by selecting adding the chart using the `disk.io` context and then selecting the "instances" that you want to be displayed on the specific chart (you can also add a chart over all nodes and also filter by node)

https://user-images.githubusercontent.com/82235632/234506179-3fb5368b-6239-4648-a3ea-ad5fb2231c80.mp4

> Below screenshots shows old charts at top, while new charts at bottom with blank title, not identifying actual node

There is still this issue with the name, now you can do it with a text label but it isn't very helpful since it take too much space on the dashboard. There is a bug/feature request about allowing users to rename the dashboards https://github.com/netdata/netdata-cloud/issues/727

let me know if the 1st point allowed to select the specific chart you wanted, so we can close this bug and track the renaming issue on the above mentioned bug

**Comment by hugovalente-pm** [comment]
@ced1check closing this, if you still have some issue with this just let us know
