### ISSUE TITLE
[Bug]: IPMI collector fails without any alert notification

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata-cloud#840]
### Bug description

A user reported that the IPMI collector (freeipmi plugin) failed and did not raise any alert notification that it had failed. On restarting the Netdata agent the data collection resumed. 

### Expected behavior

1. The IPMI plugin should not fail or become degraded. 
2. If it does happen to fail there must be an alert to notify the user that this has happened and how to fix the problem.

### Steps to reproduce

1. N/A

### Screenshots

N/A

### Error Logs

N/A

### Desktop

N/A

### Additional context

As shared by @ilyam8 the below improvement should also be tackled as part of this.

> **_we also need to change it from a dimension per sensor to a chart with labels per sensor. This way we can add sensor name/type to the alarm info line._**

**Comment by ilyam8** [comment]
@shyamvalsan 

> The IPMI plugin should not fail 

The plugin exits every 4 hours and sometimes Netdata wouldn't restart it because of a bug in reaping child processes. 

> **Note**: exits every 4 hours
> This is an old pattern we keep following - I think the idea is to prevent a memory leak if any (exit frees memory used by a process).

This was fixed (workaround) in https://github.com/netdata/netdata/pull/15140. The proper fix is https://github.com/netdata/netdata/pull/15113 (but having that workaround is enough so we can call it fixed already).

> If it does happen to fail there must be an alert to notify the user that this has happened 

Alarm added in https://github.com/netdata/netdata/pull/15151.

> and how to fix the problem

This is not fixed. We don't put such data in `info` (supposed to be short), even if we did I see the Info column is hidden Cloud->Alerts.
