### ISSUE TITLE
[Feat]: expand cassandra filter option with cluster name options.

### ISSUE THREAD

**Issue by zyxep** [netdata/netdata-cloud#841]
### Problem

When having a war room for e.g. cassandra where I have all my cassandra nodes added in so they are easier to "filter" through, i discovered it's annoying to filter which cluster of cassandra you want to see metrics for.

My "workaround" has been to just select the nodes in the nodes list and then see metrics but i feel that's annoying.

### Description

In the cassandra module/plugin, fetch the name by looking in `/etc/cassandra/cassandra.yaml` and search for the value `cluster_name:` and then fetch the content.

Then somewhere in the generic filter list have that listed and then it will sort all other metrics based on the cluster name.
That will be linked up to all relevant nodes as well.

### Importance

really want

### Value proposition

this is more of a UX thing that just makes it simpler and faster to filter metrics based on a `cluster_name` when having multiple nodes added in a war room.

**Comment by hugovalente-pm** [comment]
this is a nice request and indeed it feels more of a filtering enhancement, where maybe we need to expose more option on the current Global filter
there some discussions and around this on public ticket:
* https://github.com/netdata/netdata-cloud/issues/681
* https://github.com/netdata/netdata-cloud/issues/697 this is more for a custom dashboard

**Comment by hugovalente-pm** [comment]
@zyxep, not saying that we don't need to look to the above feature requests, but we've recently allowed the global node filter to use host labels if you had your cluster_name as part of the nodes host labels would this be a possibility?
 
 
![image](https://github.com/netdata/netdata-cloud/assets/82235632/6a6b1362-c115-4784-96c3-617dd7f14f36)


btw, closing this one since we have the above tickets open
