### ISSUE TITLE
[Bug]:  no spaces found

### ISSUE THREAD

**Issue by zegar7** [netdata/netdata-cloud#893]
### Bug description

Logging into netdata.cloud and getting an error

### Expected behavior

Site working properly

### Steps to reproduce

1. I don't really know

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/117838892/2919a02f-0064-41cf-867d-6ecd872da0a7)
![image](https://github.com/netdata/netdata-cloud/assets/117838892/f5dd05a9-22c3-4700-b9c7-0e1a218009db)

### Error Logs

https://anonfiles.com/lam6r248zf/app_netdata_cloud_har

### Desktop

OS: Windows, Android
Browser: Chrome
Browser Version: 115.0.5790.102 (Windows), 114.0.5735.196 (Android)

### Additional context

Started happening when I linked my docker container netdata to my account.
Oh and I might add, I can access the netdata panel through the local IP adress just fine

**Comment by hugovalente-pm** [comment]
@zegar7 we found the bug, this happens because with the release of the new UI on the Agent dashboard we introduced a new type of Space - a virtual space - that maps to the local agent dashboard you're looking at but this isn't a physical space

on Cloud we have the rule that a user account needs to be always linked to a physical Space (since Cloud don't know/store the virtual one), we noticed that you had deleted your physical space so that rule was broken

example:
**From Cloud**
| | |
|:--:|:--:|
| ![image](https://github.com/netdata/netdata-cloud/assets/82235632/376fb1db-1bf8-4517-92fd-4f934862fe2d) |  ![image](https://github.com/netdata/netdata-cloud/assets/82235632/39aa7b0c-df58-4a2a-97eb-96e8b25103be) |

**From local agent dashboard (after sign-in to Cloud)**
| | |
|:--:|:--:|
| ![image](https://github.com/netdata/netdata-cloud/assets/82235632/413a09aa-206e-467d-8b35-250bede7c9ca) |  ![image](https://github.com/netdata/netdata-cloud/assets/82235632/617935a8-5203-435a-a4fe-fe44b46798af) |



the fixes:
* we will review the rule to not consider the virtual Space, so to not allow the deletion of the last physical space
* trigger a recreation of your physical space that is default one created together with your account

**Comment by hugovalente-pm** [comment]
this is fixed
