### ISSUE TITLE
[Feat]: ability to create silencing rule based on alert status

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#909]
### Problem

it could be useful to be able to just have a silencing rule warning alerts of some type for example. So it would be good to be able to use alert status in the definitions of silencing rules

this would have been useful in this real question from a user: https://discord.com/channels/847502280503590932/1141451451827236904

![image](https://github.com/netdata/netdata-cloud/assets/2178292/c0068ced-bfca-4426-9033-4bd990027b90)

### Description

ability to use the alert status too when defining a silencing rule. 

### Importance

really want

### Value proposition

1. improve flexibility on alert management

**Comment by andrewm4894** [comment]
somewhat related https://github.com/netdata/netdata-cloud/issues/908

**Comment by vkuznecovas** [comment]
The creation/update endpoints for silencing rules support a `severities` property. 

Here's an example:
```json
...
 "severities": ["CRITICAL", "WARNING"]
...
```

This would match(and silence) all alerts whose status is either critical or warning. 

Supported values for severities are: `NULL`, `UNKNOWN`, `REMOVED`, `NOT_A_NUMBER`,  `CLEAR`, `WARNING`, `CRITICAL`, although I'm not sure all of them are useful. I would probably just expose the `WARNING` &  `CRITICAL` on the FE, but this is more of a @netdata/product question.

Passing the ball to @netdata/cloud-fe

**Comment by hugovalente-pm** [comment]
> Supported values for severities are: NULL, UNKNOWN, REMOVED, NOT_A_NUMBER, CLEAR, WARNING, CRITICAL, although I'm not sure all of them are useful. I would probably just expose the WARNING & CRITICAL on the FE, but this is more of a @netdata/product question.

I agree that not all are needed since not all trigger a notification. From my understanding notifications are triggered when a transition exists from/to `WARNING` or `CRITICAL` but perhaps @car12o can confirm

@vkuznecovas can you confirm if from the silencing perspective it means the logic means "Don't send me notifications on transitions to ..." as an example, if user defines silence for `WARNING` notifications wouldn't be sent for the following transitions _anything_ --> `WARNING`  but if there is a `WARNING` --> `CRITICAL` they would be sent

**Comment by car12o** [comment]
> I agree that not all are needed since not all trigger a notification. From my understanding notifications are triggered when a transition exists from/to WARNING or CRITICAL but perhaps @car12o can confirm

These are the status that trigger notifications `WARNING` `CRITICAL` `CLEAR`, and I agree only these should be available to create silencing rules.

**Comment by vkuznecovas** [comment]
> @vkuznecovas can you confirm if from the silencing perspective it means the logic means "Don't send me notifications on transitions to ..." as an example, if user defines silence for WARNING notifications wouldn't be sent for the following transitions anything --> WARNING but if there is a WARNING --> CRITICAL they would be sent

That is indeed how it works.

**Comment by hugovalente-pm** [comment]
@vkuznecovas one final question, does this allow multiple selection? meaning I want to silence, for example, `CLEAR` and `WARNING` and just get the `CRITICAL`.

@kapantzak this is about adding a new attribute on the alert related attributes: modal and table
since this is already available do you think we could slot it in between other work?

![image](https://github.com/netdata/netdata-cloud/assets/82235632/6d62c84f-2e37-4c54-aafe-aa41d4bd931d)


![image](https://github.com/netdata/netdata-cloud/assets/82235632/7d63c2c6-8aa7-4996-9716-2aa481853464)

**Comment by kapantzak** [comment]
Sure @hugovalente-pm , we'll find a way to address this soon

**Comment by vkuznecovas** [comment]
> @vkuznecovas one final question, does this allow multiple selection? meaning I want to silence, for example, CLEAR and WARNING and just get the CRITICAL.


Yes, multiple selections are supported.

**Comment by hugovalente-pm** [comment]
this is done
