### ISSUE TITLE
[Bug]: Can't select nodes for Dashboard

### ISSUE THREAD

**Issue by BlueZebra-Toulouse** [netdata/netdata-cloud#910]
### Bug description

Can't select nodes when adding Dashboard
"No nodes" message instead of dropdown

### Expected behavior

A dropdown for selecting nodes

### Steps to reproduce

1.Add dashboard

### Screenshots

<img width="709" alt="Capture d’écran 2023-08-18 à 07 28 34" src="https://github.com/netdata/netdata-cloud/assets/5279594/5d693206-f8c3-4a1f-80b4-f2d915ca7071">

### Desktop

Browser Version [e.g. 22]

**Comment by novykh** [comment]
Thanks for reporting this. Actually, you don't have to worry about this, since you do not select nodes at this stage. You can change the nodes selection from the global nodes filter at the top right corner (header) of the page, and/or add specific nodes on each chart you add to your dashboard.

The issue that you are showing it's just a missing illustration/image with the wrong alt/title on the image tag. It will be fixed on the next release, but it's not blocking you from creating your dashboard, it just messes with you and me.

If you have any other issue with the dashboards or anything else, please update this issue or open a new one, will be happy to help.
