### ISSUE TITLE
[Bug]: No emails received about alert.

### ISSUE THREAD

**Issue by cacraig** [netdata/netdata-cloud#984]
### Bug description

- No emails received about alert despite settings that allow for them.

### Expected behavior

- Should receive emails.

### Steps to reproduce

1.

### Screenshots

<img width="868" alt="Screenshot 2024-03-04 at 5 51 31 PM" src="https://github.com/netdata/netdata-cloud/assets/3621157/e06a2d50-c6c9-48ac-a056-be7dbea02375">
<img width="594" alt="Screenshot 2024-03-04 at 5 52 07 PM" src="https://github.com/netdata/netdata-cloud/assets/3621157/eff40350-a545-425d-94a8-b92e7eddb655">
<img width="1451" alt="Screenshot 2024-03-04 at 5 53 03 PM" src="https://github.com/netdata/netdata-cloud/assets/3621157/8e3813bb-c167-478f-afa3-43e93380355f">

### Desktop

OS: [Ubuntu 22.04]

**Comment by hugovalente-pm** [comment]
@cacraig could you please share your email address so we can track this from our email sending tool? send it to hugo@netdata.cloud please

**Comment by hugovalente-pm** [comment]
@cacraig looking to the alert definition you shared (below) and the events generated on the alerts everything seems correct
the alert was changing status too often to immediately send a notifications, as it has notifications delays on its config

```
delay: up 2m down 2m multiplier 1 max 1h
````
then it stabilizes on clear and we triggered the notification process, but since we don't send clear notification unless an active status (warning critical) was previously sent, the notifications was filtered out

hope this helps cçlarify things

events
![Image](https://github.com/netdata/netdata-cloud/assets/82235632/8c6d5270-76a2-4f8f-bc4c-9976e86fed2a)



<details>

<summary> alert definition </summary>

```
    alarm: tcp_errs
       on: ip.tcperrors
    class: Errors
     type: System
component: Network
       os: linux
    hosts: *
   lookup: average -30s unaligned absolute of RetransSegs
    units: errors
    every: 10s
     warn: $this > 250
     crit: $this > 800
    delay: up 2m down 2m multiplier 1 max 1h
  summary: System TCP errors
     info: IPv4 TCP errors
       to: sysadmin
```

</details>
